// <auto-generated />
using CoE.Ideas.Shared.ServiceBus;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace CoE.Ideas.Shared.Migrations
{
    [DbContext(typeof(ServiceBusEmulatorContext))]
    partial class ServiceBusEmulatorContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CoE.Ideas.Shared.ServiceBus.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedDateUtc");

                    b.Property<string>("Label")
                        .HasMaxLength(128);

                    b.Property<string>("LockToken");

                    b.HasKey("Id");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("CoE.Ideas.Shared.ServiceBus.MessageProperty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Key")
                        .HasMaxLength(128);

                    b.Property<Guid>("MessageId");

                    b.Property<string>("Value")
                        .HasMaxLength(1024);

                    b.Property<string>("ValueType")
                        .HasMaxLength(1024);

                    b.HasKey("Id");

                    b.ToTable("MessageProperties");
                });
#pragma warning restore 612, 618
        }
    }
}
