using System;
using System.Collections.Generic;
using System.Text;

namespace CoE.Issues.Core.Remedy
{
    public class Incident
    {
        public string ENTRY_ID { get; set; }
        //public long SEND_PAGE_ { get; set; } Always null
        public string SUBMITTER { get; set; }
        public long SUBMIT_DATE { get; set; }
        public string ASSIGNEE_LOGIN_ID { get; set; }
        public string LAST_MODIFIED_BY { get; set; }
        public long LAST_MODIFIED_DATE { get; set; }
        public long STATUS { get; set; }
        //public string SHORT_DESCRIPTION { get; set; }  -- Always "."
        public string SUBMITTED_PRODCAT_TIER1 { get; set; }
        public string SUBMITTED_PRODCAT_TIER2 { get; set; }
        public string SUBMITTED_PRODCAT_TIER3 { get; set; }
        public string SUBMITTED_PRODCAT_PRODNAME { get; set; }
        public string VENDOR_NAME { get; set; }
        public string RESOLUTION_CATEGORY { get; set; }
        public string OWNER_SUPPORT_COMPANY { get; set; }
        public string OWNER_GROUP_ID { get; set; }
        public string LOOKUPKEYWORD { get; set; }
        public string OWNER_GROUP { get; set; }
        public string IMPACT_OR_ROOT { get; set; }
        public string ASSIGNEE_GROUPS { get; set; }
        public string HPD_CI_FORMNAME { get; set; }
        public string STATUS_REASON2 { get; set; }
        public string ASSIGNED_GROUP_SHIFT_NAME { get; set; }
        public long SHIFTS_FLAG { get; set; }
        public string INSTANCEID { get; set; }
        public string ASSIGNED_GROUP_SHIFT_ID { get; set; }
        public long CURRENTSTAGENUMBER { get; set; }
        public string OWNER_SUPPORT_ORGANIZATION { get; set; }
        public long DO_NOT_ARCHIVE { get; set; }
        public long ORIGINAL_LAST_MODIFIED_DATE { get; set; }
        public string RESOLUTION { get; set; }
        public string ADDITIONAL_LOCATION_DETAILS { get; set; }
        public long STATUS_REASON { get; set; }
        public string DETAILED_DECRIPTION { get; set; }
        public string STATUS_INCIDENT { get; set; }
        public string CURRENTSTAGE { get; set; }
        public string COST_CENTER { get; set; }
        public long PRIORITY_WEIGHT { get; set; }
        public long URGENCY { get; set; }
        public long IMPACT { get; set; }
        public string INCIDENT_NUMBER { get; set; }
        public long PRIORITY { get; set; }
        public string ASSIGNEE { get; set; }
        public string ASSIGNED_GROUP { get; set; }
        public long REPORTED_SOURCE { get; set; }
        public string ASSIGNED_SUPPORT_COMPANY { get; set; } 
        public string Z1D_SERVICEHEALTH { get; set; }
        public string VENDOR_PHONE { get; set; }
        public long VIP { get; set; }
        public long CONTACT_SENSITIVITY { get; set; }
        public long Z1D_TOTALBREACHEDINCIDENTSCOUN { get; set; }
        public string LOCAL_PHONE { get; set; }
        public string EXTENSION { get; set; }
        public string COUNTRY_CODE { get; set; }
        public string AREA_CODE { get; set; }
        public string LAST_NAME { get; set; }
        public string FIRST_NAME { get; set; }
        public string FULL_NAME { get; set; }
        public string COMPONENT_ID { get; set; }
        public long CONTACT_CLIENT_TYPE { get; set; }
        public string MIDDLE_INITIAL { get; set; }
        public string ORGANIZATION { get; set; }
        public string TEMPLATEID { get; set; }
        public string FLAG_CREATE_REQUEST { get; set; }
        public string ASSIGNED_SUPPORT_ORGANIZATION { get; set; }
        public string COUNTRY { get; set; }
        public string STATE_PROVINCE { get; set; }
        public string DESCRIPTION { get; set; }
        public string COMPANY { get; set; }
        public string CITY { get; set; }
        public string PHONE_NUMBER { get; set; }
        public string PRODUCT_MODEL_VERSION { get; set; }
        public string PRODUCT_NAME { get; set; }
        public string MANUFACTURER { get; set; }
        public string CATEGORIZATION_TIER_1 { get; set; }
        public string INTERNET_E_MAIL { get; set; }
        public string CORPORATE_ID { get; set; }
        public string GEONET { get; set; }
        public string DESK_LOCATION { get; set; }
        public string ZIP_POSTAL_CODE { get; set; }
        public string MAIL_STATION { get; set; }
        public string STREET { get; set; }
        public string KMSGUID { get; set; }
        public string CONTACT_COMPANY { get; set; }
        public string PERSON_ID { get; set; }
        public string SITE_ID { get; set; }
        public string ASSIGNED_GROUP_ID { get; set; }
        public string CATEGORIZATION_TIER_2 { get; set; }
        public string CATEGORIZATION_TIER_3 { get; set; }
        public string HR_ID { get; set; }
        public string REGION { get; set; }
        public string PRODUCT_CATEGORIZATION_TIER_1 { get; set; }
        public long Z1D_TOTALCRITICALINCIDENTSCOUN { get; set; }
        public string SITE_GROUP { get; set; }
        public long STATUS_PPL { get; set; }
        public string DEPARTMENT { get; set; }
        public string PRODUCT_CATEGORIZATION_TIER_3 { get; set; }
        public string PRODUCT_CATEGORIZATION_TIER_2 { get; set; }
        public string CI_TAG_NUMBER { get; set; }
        public string SERVICE_TYPE { get; set; }
        public string SRID { get; set; }
        public string SATISFACTION_RATING { get; set; }
        public long ESCHAT_SET_AUTO_ASSIGN { get; set; }
        public string Z1D_CI_FORMNAME { get; set; }
        public string PREVIOUSSTATUS { get; set; }
        public string Z1D_VISPROCESSFLOWVIEW { get; set; }
        public string SERVICECI { get; set; }
        public string LOGIN_ID { get; set; }
        public string CHAT_SESSION_ID { get; set; }
        public string DIRECT_CONTACT_SITE_ID { get; set; }
        public string DIRECT_CONTACT_MAIL_STATION { get; set; }
        public string DIRECT_CONTACT_LOCATION_DETAIL { get; set; }
        public string DIRECT_CONTACT_LOCAL_NUMBER { get; set; }
        public string DIRECT_CONTACT_EXTENSION { get; set; }
        public string DIRECT_CONTACT_COUNTRY_CODE { get; set; }
        public string DIRECT_CONTACT_AREA_CODE { get; set; }
        public string DIRECT_CONTACT_COUNTRY { get; set; }
        public string DIRECT_CONTACT_STATE_PROVINCE { get; set; }
        public string DIRECT_CONTACT_STREET { get; set; }
        public string DIRECT_CONTACT_TIME_ZONE { get; set; }
        public string DIRECT_CONTACT_DESK_LOCATION { get; set; }
        public string DIRECT_CONTACT_CITY { get; set; }
        public string SERVICECI_CLASS { get; set; }
        public string DIRECT_CONTACT_ZIP_POSTAL_CODE { get; set; }
        public string SLA_BREACH_EXCEPTION { get; set; }
        public long CREATED_FROM_TEMPLATE { get; set; }
        public long CLOSURE_SOURCE { get; set; }
        public string CLOSURE_MANUFACTURER { get; set; }
        public string Z2AF_WORK_LOG03001 { get; set; }
        public string SLA_BREACH_REASON { get; set; }
        public string RESOLUTION_CATEGORY_TIER_3 { get; set; }
        public string CLOSURE_PRODUCT_CATEGORY_TIER1 { get; set; }
        public string RESOLUTION_METHOD { get; set; }
        public string RESOLUTION_CATEGORY_TIER_2 { get; set; }
        public string CLOSURE_PRODUCT_NAME { get; set; }
        public string Z2AF_WORK_LOG01001 { get; set; }
        public long KICKBACK_COUNT { get; set; }
        public string CLOSURE_PRODUCT_MODEL_VERSION { get; set; }
        public string Z2AF_WORK_LOG02001 { get; set; }
        public string CLOSURE_PRODUCT_CATEGORY_TIER2 { get; set; }
        public string HPD_CI { get; set; }
        public string CLOSURE_PRODUCT_CATEGORY_TIER3 { get; set; }
        public string LAST_NAME2 { get; set; }
        public string SUPPORT_GROUP_ROLE { get; set; }
        public long ENABLE_ASSIGNMENT_ENGINE { get; set; }
        public string ATTACHMENT { get; set; }
        public string CELL_NAME { get; set; }
        public string DIRECT_CONTACT_ORGANIZATION { get; set; }
        public string DIRECT_CONTACT_DEPARTMENT { get; set; }
        public string DIRECT_CONTACT_MIDDLE_INITIAL { get; set; }
        public string DIRECT_CONTACT_PHONE_NUMBER { get; set; }
        public string DIRECT_CONTACT_SITE { get; set; }
        public string DIRECT_CONTACT_PERSON_ID { get; set; }
        public string DIRECT_CONTACT_REGION { get; set; }
        public string DIRECT_CONTACT_SITE_GROUP { get; set; }
        public string TEMPLATEGUID { get; set; }
        public string DIRECT_CONTACT_LAST_NAME { get; set; }
        public string DIRECT_CONTACT_FIRST_NAME { get; set; }
        public string DIRECT_CONTACT_COMPANY { get; set; }
        public string FIRST_NAME2 { get; set; }
        public long GROUP_TRANSFERS { get; set; }
        public long TOTAL_TRANSFERS { get; set; }
        public long INDIVIDUAL_TRANSFERS { get; set; }
        public string VENDOR_LAST_NAME { get; set; }
        public string VENDOR_FIRST_NAME { get; set; }
        public string VENDOR_EMAIL { get; set; }
        public long VENDOR_RESPONDED_ON { get; set; }
        public string VENDOR_PERSON_ID { get; set; }
        public long VENDOR_RESOLVED_DATE { get; set; }
        public long VENDOR_GROUP2 { get; set; }
        public long LAST_KICKBACK_DATE { get; set; }
        public string VENDOR_LOGIN_ID { get; set; }
        public string Z2AF_WORK_LOG01002 { get; set; }
        public long VENDOR_ASSIGNMENT_STATUS { get; set; }
        public long INCAUTOCLOSERESOLVED_SEC { get; set; }
        public long CREATE_IMPACTED_AREA_FROM_CUST { get; set; }
        public string OPTIONFORCLOSINGINCIDENT { get; set; }
        public long Z1D_VENDORACCESS { get; set; }
        public long REQUIRED_RESOLUTION_DATETIME { get; set; }
        public long SLA_RES_BUSINESS_HOUR_SECONDS { get; set; }
        public string CLIENTLOCALE { get; set; }
        public string Z2AF_WORK_LOG02002 { get; set; }
        public string Z2AF_WORK_LOG03002 { get; set; }
        public string VENDOR_GROUP_ID { get; set; }
        public long ZD_NEXTDUEDATE_TIME { get; set; }
        public string VENDOR_ORGANIZATION { get; set; }
        public string VENDOR_GROUP { get; set; }
        public long ASSIGNMENT_METHOD { get; set; }
        public string BORPHANEDROOT { get; set; }
        public string Z1D_VISTARGETFORM { get; set; }
        public long OUTBOUND { get; set; }
        public long INBOUND { get; set; }
        public string HPD_TEMPLATE_ID { get; set; }
        public long DR { get; set; }
        public long EH { get; set; }
        public string SERVICECI_RECONID { get; set; }
        public string BIIARS_03 { get; set; }
        public long ESCALATED_ { get; set; }
        public string RETURN_CODE { get; set; }
        public string SRINSTANCEID { get; set; }
        public long SLA_RESPONDED { get; set; }
        public long OLA_HOLD { get; set; }
        public string SLMEVENTLOOKUPTBLKEYWORD { get; set; }
        public long RESOLUTION_START_DATE { get; set; }
        public string BIIARS_02 { get; set; }
        public long ACKNOWLEDGMENT_START_DATE { get; set; }
        public long UNKNOWNUSER { get; set; }
        public string REASON_DESCRIPTION { get; set; }
        public string POLICY_TYPE { get; set; }
        public string WEB_INCIDENT_ID { get; set; }
        public long ESTIMATED_RESOLUTION_DATE { get; set; }
        public string ROOT_INCIDENT_ID_LIST { get; set; }
        public string BIIARS_01 { get; set; }
        public string REASON_CODE { get; set; }
        public string MC_UEID { get; set; }
        public long TOTAL_FIELDS_COUNT { get; set; }
        public string LAST__ASSIGNED_DATE { get; set; }
        public long CREATED_FROM_FLAG { get; set; }
        public string ABYDOS_NOTIFY_TEXT { get; set; }
        public long ABYDOS_NOTIFY_RECIPIENT { get; set; }
        public long ABYDOS_PROCESS_VERSION { get; set; }
        public string ABYDOS_PROCESS_STATUS { get; set; }
        public long ABYDOS_USE_WIZARD_ { get; set; }
        public long ABYDOS_TASKS_GENERATED { get; set; }
        public string ACTIVE_TASKS { get; set; }
        public long SLM_PRIORITY { get; set; }
        public string DIRECT_CONTACT_INTERNET_E_MAIL { get; set; }
        public long TICKETTYPE { get; set; }
        public string USE_CASE { get; set; }
        public string SLMLOOKUPTBLKEYWORD { get; set; }
        public long BROADCASTED_FLAG { get; set; }
        public string CI { get; set; }
        public string ASSIGNEE_SELECT_FORM { get; set; }
        public string ABYDOS_PROCESS_NAME { get; set; }
        public string ABYDOS_TEMPLATE_ID { get; set; }
        public string ABYDOS_SLA_NAME { get; set; }
        public long ABYDOS_AUDITFLAG { get; set; }
        public string COMMAND { get; set; }
        public string Z1D_VISFORMVIEW { get; set; }
        public string DIRECT_CONTACT_CORPORATE_ID { get; set; }
        public string Z1D_TEMPLATE_NAME { get; set; }
        public string ROOT_COMPONENT_ID_LIST { get; set; }
        public string VENDOR_ASSIGNEE_GROUPS { get; set; }
        public string USER_ID_PERMISSIONS { get; set; }
        public string GLOBAL_OR_CUSTOM_MAPPING { get; set; }
        public string SERVICE { get; set; }
        public string POLICY_NAME { get; set; }
        public string CREATED_BY { get; set; }
        public string ROOTREQUESTNAME { get; set; }
        public string PATCH_LAST_BUILD_ID { get; set; }
        public long ASSIGN_TO_VENDOR { get; set; }
        public long CATEGORY { get; set; }
        public string HPD_CI_RECONID { get; set; }
        public long REPRODUCEABLE_FLAG { get; set; }
        public long EFFORTDURATIONHOUR { get; set; }
        public string ORIGINAL_LAST_MODIFIED_BY { get; set; }
        public string SRMSAOIGUID { get; set; }
        public long SLM_STATUS { get; set; }
        public long INFRASTRUCTURE_CHG_INITIATED { get; set; }
        public string SITE { get; set; }
        public long INFRASTRUCTUREEVENTTYPE { get; set; }
        public string SRMS_REGISTRY_INSTANCE_ID { get; set; }
        public string VENDOR_CONTACT { get; set; }
        public string Z1G_DEFAULTVUI { get; set; }
        public string ORIGINAL_INCIDENT_NUMBER { get; set; }
        public long REPORTED_TO_VENDOR { get; set; }
        public long INCIDENT_ASSOCIATION_TYPE { get; set; }
        public string CUSTOMER_LOGIN_ID { get; set; }
        public string VENDOR_TICKET_NUMBER { get; set; }
        public long EFFORT_TIME_SPENT_MINUTES { get; set; }
        public string SHOW_FOR_PROCESS { get; set; }
        public string DIRECT_CONTACT_LOGIN_ID { get; set; }
        public long TOTAL_TIME_SPENT { get; set; }
        public string OWNER { get; set; }
        public string ASSOCIATION_DESCRIPTION { get; set; }
        public string OWNER_LOGIN_ID { get; set; }
        public string GENERIC_CATEGORIZATION_TIER_3 { get; set; }
        public string STAGECONDITION { get; set; }
        public string GENERIC_CATEGORIZATION_TIER_1 { get; set; }
        public string GENERIC_CATEGORIZATION_TIER_2 { get; set; }
        public string ASSIGNEE_ID { get; set; }
        public string TIME_ZONE { get; set; }
        public string BIIARS_05 { get; set; }
        public long ONWER_GROUP_USES_SLA { get; set; }
        public string SEV1SERVICE { get; set; }
        public string PREVIOUS_ORGANIZATION { get; set; }
        public long ASSIGNED_GROUP_USES_OLA { get; set; }
        public long LAST_ACKNOWLEDGED_DATE { get; set; }
        public long LAST_RESOLVED_DATE { get; set; }
        public long REPORTED_DATE { get; set; }
        public long RESPONDED_DATE { get; set; }
        public long RE_OPENED_DATE { get; set; }
        public long SLA_HOLD { get; set; }
        public long CLOSED_DATE { get; set; }
        public long LAST_SLA_HOLD_DATE { get; set; }
        public long NEXT_TARGET_DATE { get; set; }
        public long TOTAL_ESCALATION_LEVEL { get; set; }
        public long TOTAL_OLA_RESOLUTION_ESC_LEVEL { get; set; }
        public long TOTAL_OLA_ACKNOWLEDGEESC_LEVEL { get; set; }
        public long INITAL_ASSIGNED_DATE { get; set; }
        public string SLM_MESSAGE_BODY__C { get; set; }
        public string SLM_SUBJECT { get; set; }
        public string SRATTACHMENT { get; set; }
        public string COE_SUBMITTERDEFAULTGROUP { get; set; }
        public string DATATAGS { get; set; }
        public long LAST_DATE_DURATION_CALCULATED { get; set; }
        public string BIIARS_04 { get; set; }
    }
}
