//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoE.Issues.Remedy.Watcher.RemedyServiceReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:COE_HPD_Incident_Search_Octava", ConfigurationName="CoE.Issues.Remedy.Watcher.RemedyServiceReference.New_Port_0PortType")]
    public interface New_Port_0PortType
    {
        
        // CODEGEN: Generating message contract since message New_Get_Operation_0Request has headers
        [System.ServiceModel.OperationContractAttribute(Action="urn:COE_HPD_Incident_Search_Octava/New_Get_Operation_0", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        CoE.Issues.Remedy.Watcher.RemedyServiceReference.New_Get_Operation_0Response New_Get_Operation_0(CoE.Issues.Remedy.Watcher.RemedyServiceReference.New_Get_Operation_0Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:COE_HPD_Incident_Search_Octava/New_Get_Operation_0", ReplyAction="*")]
        System.Threading.Tasks.Task<CoE.Issues.Remedy.Watcher.RemedyServiceReference.New_Get_Operation_0Response> New_Get_Operation_0Async(CoE.Issues.Remedy.Watcher.RemedyServiceReference.New_Get_Operation_0Request request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:COE_HPD_Incident_Search_Octava")]
    public partial class AuthenticationInfo
    {
        
        private string userNameField;
        
        private string passwordField;
        
        private string authenticationField;
        
        private string localeField;
        
        private string timeZoneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string userName
        {
            get
            {
                return this.userNameField;
            }
            set
            {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string authentication
        {
            get
            {
                return this.authenticationField;
            }
            set
            {
                this.authenticationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string locale
        {
            get
            {
                return this.localeField;
            }
            set
            {
                this.localeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string timeZone
        {
            get
            {
                return this.timeZoneField;
            }
            set
            {
                this.timeZoneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:COE_HPD_Incident_Search_Octava")]
    public partial class OutputMapping1GetListValues
    {

        private string descriptionField;

        private string detailed_DecriptionField;

        private System.DateTime submit_DateField;

        private StatusType statusField;

        private string incident_NumberField;

        private System.DateTime last_Modified_DateField;

        private System.Nullable<UrgencyType> urgencyField;

        private string submitterField;

        private string assignee_Login_IDField;

        private string corporate_IDField;

        private string owner_GroupField;


        public OutputMapping1GetListValues()
        {
          
            this.submitterField = "$USER$";
            this.statusField = StatusType.New;

        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 47)]
        public string Owner_Group
        {
            get
            {
                return this.owner_GroupField;
            }
            set
            {
                this.owner_GroupField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public string Assignee_Login_ID
        {
            get
            {
                return this.assignee_Login_IDField;
            }
            set
            {
                this.assignee_Login_IDField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string Submitter
        {
            get
            {
                return this.submitterField;
            }
            set
            {
                this.submitterField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 111)]
        public System.Nullable<UrgencyType> Urgency
        {
            get
            {
                return this.urgencyField;
            }
            set
            {
                this.urgencyField = value;
            }
        }
        [System.Xml.Serialization.XmlElementAttribute(Order = 8)]
        public System.DateTime Last_Modified_Date
        {
            get
            {
                return this.last_Modified_DateField;
            }
            set
            {
                this.last_Modified_DateField = value;
            }
        }
        [System.Xml.Serialization.XmlElementAttribute(Order = 153)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        [System.Xml.Serialization.XmlElementAttribute(Order = 91)]
        public string Detailed_Decription
        {
            get
            {
                return this.detailed_DecriptionField;
            }
            set
            {
                this.detailed_DecriptionField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public System.DateTime Submit_Date
        {
            get
            {
                return this.submit_DateField;
            }
            set
            {
                this.submit_DateField = value;
            }
        }


        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 10)]
        public StatusType Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        [System.Xml.Serialization.XmlElementAttribute(Order = 113)]
        public string Incident_Number
        {
            get
            {
                return this.incident_NumberField;
            }
            set
            {
                this.incident_NumberField = value;
            }
        }


    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:COE_HPD_Incident_Search_Octava")]
    public enum Send_Page_Type
    {
        
        /// <remarks/>
        Yes,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:COE_HPD_Incident_Search_Octava")]
    public enum StatusType
    {
        
        /// <remarks/>
        New,
        
        /// <remarks/>
        Assigned,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("In Progress")]
        InProgress,
        
        /// <remarks/>
        Pending,
        
        /// <remarks/>
        Resolved,
        
        /// <remarks/>
        Closed,
        
        /// <remarks/>
        Cancelled,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:COE_HPD_Incident_Search_Octava")]
    public enum z1D_TypeSelector2Type
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Task Template")]
        TaskTemplate,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Task Group Template")]
        TaskGroupTemplate,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Ad hoc")]
        Adhoc,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:COE_HPD_Incident_Search_Octava")]
    public enum z1G_Contact_Name_FormatType
    {
        
        /// <remarks/>
        FML,
        
        /// <remarks/>
        LFM,
        
        /// <remarks/>
        LF,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:COE_HPD_Incident_Search_Octava")]
    public enum z1D_AssociationType02Type
    {
        
        /// <remarks/>
        ALL,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Duplicate of")]
        Duplicateof,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Original of")]
        Originalof,
        
        /// <remarks/>
        Peer,
        
        /// <remarks/>
        Uses,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Used by")]
        Usedby,
        
        /// <remarks/>
        Owns,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Owned by")]
        Ownedby,
        
        /// <remarks/>
        Supports,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Supported by")]
        Supportedby,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Connected to")]
        Connectedto,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Backs up")]
        Backsup,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Backed up by")]
        Backedupby,
        
        /// <remarks/>
        Upstream,
        
        /// <remarks/>
        Downstream,
        
        /// <remarks/>
        Caused,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Caused by")]
        Causedby,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Corrected by")]
        Correctedby,
        
        /// <remarks/>
        Corrects,
        
        /// <remarks/>
        Initiates,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Initiated by")]
        Initiatedby,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Runs on")]
        Runson,
        
        /// <remarks/>
        Runs,
        
        /// <remarks/>
        Orders,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Ordered by")]
        Orderedby,
        
        /// <remarks/>
        Investigates,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Investigated by")]
        Investigatedby,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Re-opened by")]
        Reopenedby,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Re-opened from")]
        Reopenedfrom,
        
        /// <remarks/>
        Created,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Created by")]
        Createdby,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Attached to")]
        Attachedto,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Baseline of")]
        Baselineof,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Baselined by")]
        Baselinedby,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Related to")]
        Relatedto,
        
        /// <remarks/>
        Upgrades,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Upgraded by")]
        Upgradedby,
        
        /// <remarks/>
        Manages,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Managed by")]
        Managedby,
        
        /// <remarks/>
        Restores,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Restored by")]
        Restoredby,
        
        /// <remarks/>
        Repairs,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Repaired by")]
        Repairedby,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Predecessor of")]
        Predecessorof,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Successor of")]
        Successorof,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("License to")]
        Licenseto,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("License for")]
        Licensefor,
        
        /// <remarks/>
        Resolved,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Resolved by")]
        Resolvedby,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Cross Referenced to")]
        CrossReferencedto,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Consists of")]
        Consistsof,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Member of")]
        Memberof,
        
        /// <remarks/>
        Hosts,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Hosted by")]
        Hostedby,
        
        /// <remarks/>
        Authenticates,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Authenticated by")]
        Authenticatedby,
        
        /// <remarks/>
        Stores,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Stored in")]
        Storedin,
        
        /// <remarks/>
        Identified,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Identified by")]
        Identifiedby,
        
        /// <remarks/>
        Successor,
        
        /// <remarks/>
        Predecessor,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Impacted by")]
        Impactedby,
        
        /// <remarks/>
        Impacts,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Incompatible with")]
        Incompatiblewith,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Compatible with")]
        Compatiblewith,
        
        /// <remarks/>
        Installs,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Installed by")]
        Installedby,
        
        /// <remarks/>
        Moves,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Moved by")]
        Movedby,
        
        /// <remarks/>
        Changes,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Changed by")]
        Changedby,
        
        /// <remarks/>
        Removes,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Removed by")]
        Removedby,
        
        /// <remarks/>
        Approves,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Approved by")]
        Approvedby,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Terms and Conditions of")]
        TermsandConditionsof,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Terms and Conditions for")]
        TermsandConditionsfor,
        
        /// <remarks/>
        Bundles,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Bundled by")]
        Bundledby,
        
        /// <remarks/>
        Stocks,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Stock of")]
        Stockof,
        
        /// <remarks/>
        Dependent,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:COE_HPD_Incident_Search_Octava")]
    public enum z1D_Locked_Down2Type
    {
        
        /// <remarks/>
        Yes,
        
        /// <remarks/>
        No,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:COE_HPD_Incident_Search_Octava")]
    public enum z1D_Task_or_Task_Group2Type
    {
        
        /// <remarks/>
        Task,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Task Group")]
        TaskGroup,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:COE_HPD_Incident_Search_Octava")]
    public enum z1D_TaskType2Type
    {
        
        /// <remarks/>
        Manual,
        
        /// <remarks/>
        Automatic,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:COE_HPD_Incident_Search_Octava")]
    public enum z1G_TaskViewPreference2Type
    {
        
        /// <remarks/>
        Full,
        
        /// <remarks/>
        Minimal,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:COE_HPD_Incident_Search_Octava")]
    public enum z1D_Child_Type2Type
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Root Request")]
        RootRequest,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Task Group")]
        TaskGroup,
        
        /// <remarks/>
        Task,
        
        /// <remarks/>
        Note,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:COE_HPD_Incident_Search_Octava")]
    public enum Service_Type2Type
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("User Service Restoration")]
        UserServiceRestoration,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("User Service Request")]
        UserServiceRequest,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Infrastructure Restoration")]
        InfrastructureRestoration,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Infrastructure Event")]
        InfrastructureEvent,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:COE_HPD_Incident_Search_Octava")]
    public enum z1D_TaskGroupType2Type
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Standard\t\t\t\t#Item Name")]
        StandardItemName,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Sequencing\t\t\t\t#Item Name")]
        SequencingItemName,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:COE_HPD_Incident_Search_Octava")]
    public enum z1D_Just_Made_DuplicateType
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Yes From Duplicate Incident")]
        YesFromDuplicateIncident,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Yes From Original Incident")]
        YesFromOriginalIncident,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:COE_HPD_Incident_Search_Octava")]
    public enum z1D_Table_Request_TypeType
    {
        
        /// <remarks/>
        ALL,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Asset Configuration")]
        AssetConfiguration,
        
        /// <remarks/>
        Broadcast,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("CI Unavailability")]
        CIUnavailability,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Configuration Component")]
        ConfigurationComponent,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Configuration Item")]
        ConfigurationItem,
        
        /// <remarks/>
        Contract,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("General Broadcast")]
        GeneralBroadcast,
        
        /// <remarks/>
        Incident,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Incident Template")]
        IncidentTemplate,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Infrastructure Change")]
        InfrastructureChange,
        
        /// <remarks/>
        Task,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Infrastructure Change Template")]
        InfrastructureChangeTemplate,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Solution Database")]
        SolutionDatabase,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Known Error")]
        KnownError,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Operational Level Agreement")]
        OperationalLevelAgreement,
        
        /// <remarks/>
        People,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("People Organization")]
        PeopleOrganization,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Problem Investigation")]
        ProblemInvestigation,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Purchase Requisition")]
        PurchaseRequisition,
        
        /// <remarks/>
        Product,
        
        /// <remarks/>
        Release,
        
        /// <remarks/>
        Request,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Service Level Agreement")]
        ServiceLevelAgreement,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Support Group")]
        SupportGroup,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Asset Lease")]
        AssetLease,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Asset Maintenance")]
        AssetMaintenance,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Software Library Item")]
        SoftwareLibraryItem,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Work Order")]
        WorkOrder,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("RKM Solution")]
        RKMSolution,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:COE_HPD_Incident_Search_Octava")]
    public enum Do_Not_ArchiveType
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Do Not Archive")]
        DoNotArchive,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:COE_HPD_Incident_Search_Octava")]
    public enum CreateRecordType2Type
    {
        
        /// <remarks/>
        ALL,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Asset Configuration")]
        AssetConfiguration,
        
        /// <remarks/>
        Broadcast,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("CI Unavailability")]
        CIUnavailability,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Configuration Component")]
        ConfigurationComponent,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Configuration Item")]
        ConfigurationItem,
        
        /// <remarks/>
        Contract,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("General Broadcast")]
        GeneralBroadcast,
        
        /// <remarks/>
        Incident,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Incident Template")]
        IncidentTemplate,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Infrastructure Change")]
        InfrastructureChange,
        
        /// <remarks/>
        Task,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Infrastructure Change Template")]
        InfrastructureChangeTemplate,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Solution Database")]
        SolutionDatabase,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Known Error")]
        KnownError,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Operational Level Agreement")]
        OperationalLevelAgreement,
        
        /// <remarks/>
        People,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("People Organization")]
        PeopleOrganization,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Problem Investigation")]
        ProblemInvestigation,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Purchase Requisition")]
        PurchaseRequisition,
        
        /// <remarks/>
        Product,
        
        /// <remarks/>
        Release,
        
        /// <remarks/>
        Request,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Service Level Agreement")]
        ServiceLevelAgreement,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Support Group")]
        SupportGroup,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Asset Lease")]
        AssetLease,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Asset Maintenance")]
        AssetMaintenance,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Software Library Item")]
        SoftwareLibraryItem,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:COE_HPD_Incident_Search_Octava")]
    public enum Status_ReasonType
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Infrastructure Change Created")]
        InfrastructureChangeCreated,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Local Site Action Required")]
        LocalSiteActionRequired,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Purchase Order Approval")]
        PurchaseOrderApproval,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Registration Approval")]
        RegistrationApproval,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Supplier Delivery")]
        SupplierDelivery,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Support Contact Hold")]
        SupportContactHold,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Third Party Vendor Action Reqd")]
        ThirdPartyVendorActionReqd,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Client Action Required")]
        ClientActionRequired,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Infrastructure Change")]
        InfrastructureChange,
        
        /// <remarks/>
        Request,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Future Enhancement")]
        FutureEnhancement,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Pending Original Incident")]
        PendingOriginalIncident,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Client Hold")]
        ClientHold,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Monitoring Incident")]
        MonitoringIncident,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Customer Follow-Up Required")]
        CustomerFollowUpRequired,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Temporary Corrective Action")]
        TemporaryCorrectiveAction,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("No Further Action Required")]
        NoFurtherActionRequired,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Resolved by Original Incident")]
        ResolvedbyOriginalIncident,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Automated Resolution Reported")]
        AutomatedResolutionReported,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("No longer a Causal CI")]
        NolongeraCausalCI,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Pending Causal Incident Resolution")]
        PendingCausalIncidentResolution,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Resolved by Causal Incident")]
        ResolvedbyCausalIncident,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:COE_HPD_Incident_Search_Octava")]
    public enum z1G_UnrestrictedAccessMemberType
    {
        
        /// <remarks/>
        false_0,
        
        /// <remarks/>
        true_1,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:COE_HPD_Incident_Search_Octava")]
    public enum UrgencyType
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1-Critical")]
        Item1Critical,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2-High")]
        Item2High,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3-Medium")]
        Item3Medium,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4-Low")]
        Item4Low,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:COE_HPD_Incident_Search_Octava")]
    public enum ImpactType
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1-Extensive/Widespread")]
        Item1ExtensiveWidespread,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2-Significant/Large")]
        Item2SignificantLarge,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3-Moderate/Limited")]
        Item3ModerateLimited,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4-Minor/Localized")]
        Item4MinorLocalized,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:COE_HPD_Incident_Search_Octava")]
    public enum PriorityType
    {
        
        /// <remarks/>
        Critical,
        
        /// <remarks/>
        High,
        
        /// <remarks/>
        Medium,
        
        /// <remarks/>
        Low,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:COE_HPD_Incident_Search_Octava")]
    public enum Reported_SourceType
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Direct Input")]
        DirectInput,
        
        /// <remarks/>
        Email,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("External Escalation")]
        ExternalEscalation,
        
        /// <remarks/>
        Fax,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Self Service")]
        SelfService,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Systems Management")]
        SystemsManagement,
        
        /// <remarks/>
        Phone,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Voice Mail")]
        VoiceMail,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Walk In")]
        WalkIn,
        
        /// <remarks/>
        Web,
        
        /// <remarks/>
        Other,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("BMC Impact Manager Event")]
        BMCImpactManagerEvent,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:COE_HPD_Incident_Search_Octava")]
    public enum Contact_SensitivityType
    {
        
        /// <remarks/>
        Sensitive,
        
        /// <remarks/>
        Standard,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:COE_HPD_Incident_Search_Octava")]
    public enum Contact_Client_TypeType
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("=== Operating Company Menu ===")]
        OperatingCompanyMenu,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Office-Based Employee")]
        OfficeBasedEmployee,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Field-Based Employee")]
        FieldBasedEmployee,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Home-Based Employee")]
        HomeBasedEmployee,
        
        /// <remarks/>
        Contractor,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("======= Customer Menu =======")]
        CustomerMenu,
        
        /// <remarks/>
        Customer,
        
        /// <remarks/>
        Prospect,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("======== Vendor Menu ========")]
        VendorMenu,
        
        /// <remarks/>
        Vendor,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:COE_HPD_Incident_Search_Octava")]
    public enum Record_TypeType
    {
        
        /// <remarks/>
        ALL,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Asset Configuration")]
        AssetConfiguration,
        
        /// <remarks/>
        Broadcast,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("CI Unavailability")]
        CIUnavailability,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Configuration Component")]
        ConfigurationComponent,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Configuration Item")]
        ConfigurationItem,
        
        /// <remarks/>
        Contract,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("General Broadcast")]
        GeneralBroadcast,
        
        /// <remarks/>
        Incident,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Incident Template")]
        IncidentTemplate,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Infrastructure Change")]
        InfrastructureChange,
        
        /// <remarks/>
        Task,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Infrastructure Change Template")]
        InfrastructureChangeTemplate,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Solution Database")]
        SolutionDatabase,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Known Error")]
        KnownError,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Operational Level Agreement")]
        OperationalLevelAgreement,
        
        /// <remarks/>
        People,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("People Organization")]
        PeopleOrganization,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Problem Investigation")]
        ProblemInvestigation,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Purchase Requisition")]
        PurchaseRequisition,
        
        /// <remarks/>
        Product,
        
        /// <remarks/>
        Release,
        
        /// <remarks/>
        Request,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Service Level Agreement")]
        ServiceLevelAgreement,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Support Group")]
        SupportGroup,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Asset Lease")]
        AssetLease,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Asset Maintenance")]
        AssetMaintenance,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Software Library Item")]
        SoftwareLibraryItem,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Work Order")]
        WorkOrder,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="Status-PPLType", Namespace="urn:COE_HPD_Incident_Search_Octava")]
    public enum StatusPPLType
    {
        
        /// <remarks/>
        Proposed,
        
        /// <remarks/>
        Enabled,
        
        /// <remarks/>
        Offline,
        
        /// <remarks/>
        Obsolete,
        
        /// <remarks/>
        Archive,
        
        /// <remarks/>
        Delete,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:COE_HPD_Incident_Search_Octava")]
    public enum z1G_Use_Custom_PrefixType
    {
        
        /// <remarks/>
        Enabled,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:COE_HPD_Incident_Search_Octava")]
    public enum z1D_View_AccessType
    {
        
        /// <remarks/>
        Internal,
        
        /// <remarks/>
        Public,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:COE_HPD_Incident_Search_Octava")]
    public enum z1D_PreferredRouting_ServiceCIType
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Supported By")]
        SupportedBy,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Managed By")]
        ManagedBy,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:COE_HPD_Incident_Search_Octava")]
    public enum z1G_Reopen_IncidentType
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("New Request After Submit")]
        NewRequestAfterSubmit,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Modify Request After Submit")]
        ModifyRequestAfterSubmit,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:COE_HPD_Incident_Search_Octava")]
    public enum Closure_SourceType
    {
        
        /// <remarks/>
        Customer,
        
        /// <remarks/>
        System,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Support Agent")]
        SupportAgent,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:COE_HPD_Incident_Search_Octava")]
    public enum z1D_WorkInfo_FileDefaultMsgType
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("<File Name>")]
        FileName,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:COE_HPD_Incident_Search_Octava")]
    public enum z1G_Customer_SearchbyType
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Corporate ID")]
        CorporateID,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("First Name")]
        FirstName,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Last Name")]
        LastName,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Internet E-mail")]
        InternetEmail,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Phone Number")]
        PhoneNumber,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Login ID")]
        LoginID,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:COE_HPD_Incident_Search_Octava")]
    public enum Service_Entitlement_MethodType
    {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Customer Based")]
        CustomerBased,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("CI Based")]
        CIBased,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("CI Based - Enforce CI Tag")]
        CIBasedEnforceCITag,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:COE_HPD_Incident_Search_Octava")]
    public enum z1D_Notification_TypeType
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("People Support Staff")]
        PeopleSupportStaff,
        
        /// <remarks/>
        People,
        
        /// <remarks/>
        External,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:COE_HPD_Incident_Search_Octava")]
    public enum Vendor_Assignment_StatusType
    {
        
        /// <remarks/>
        Assigned,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("In Progress")]
        InProgress,
        
        /// <remarks/>
        Completed,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:COE_HPD_Incident_Search_Octava")]
    public enum z1D_Calculate_SLM_DurationsType
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Calculate SLM Durations")]
        CalculateSLMDurations,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:COE_HPD_Incident_Search_Octava")]
    public enum z1D_Assign_To_Current_UserType
    {
        
        /// <remarks/>
        No,
        
        /// <remarks/>
        Yes,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:COE_HPD_Incident_Search_Octava")]
    public enum z1D_Work_Log_TypeType
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("----- Customer Inbound -----")]
        CustomerInbound,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Customer Communication")]
        CustomerCommunication,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Customer Follow-up")]
        CustomerFollowup,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Customer Status Update")]
        CustomerStatusUpdate,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("----- Customer Outbound -----")]
        CustomerOutbound,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Closure Follow Up")]
        ClosureFollowUp,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Detail Clarification")]
        DetailClarification,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("General Information")]
        GeneralInformation,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Resolution Communications")]
        ResolutionCommunications,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Satisfaction Survey")]
        SatisfactionSurvey,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Status Update")]
        StatusUpdate,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("----- General -----")]
        General,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Incident Task / Action")]
        IncidentTaskAction,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Problem Script")]
        ProblemScript,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Working Log")]
        WorkingLog,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Email System")]
        EmailSystem,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Paging System")]
        PagingSystem,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("BMC Impact Manager Update")]
        BMCImpactManagerUpdate,
        
        /// <remarks/>
        Chat,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("----- Vendor -----")]
        Vendor,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Vendor Communication")]
        VendorCommunication,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:COE_HPD_Incident_Search_Octava")]
    public enum Assignment_MethodType
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("System Assigned")]
        SystemAssigned,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:COE_HPD_Incident_Search_Octava")]
    public enum z1D_Broadcast_Auto_PopupType
    {
        
        /// <remarks/>
        Never,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("On Console Open")]
        OnConsoleOpen,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("On New Broadcast")]
        OnNewBroadcast,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:COE_HPD_Incident_Search_Octava")]
    public enum Assignment_AcceleratorType
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("My Default Group")]
        MyDefaultGroup,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("My Group List")]
        MyGroupList,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Favorite Group(s)")]
        FavoriteGroups,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Auto Assign")]
        AutoAssign,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Current Owner")]
        CurrentOwner,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:COE_HPD_Incident_Search_Octava")]
    public enum UnknownUserType
    {
        
        /// <remarks/>
        True,
        
        /// <remarks/>
        False,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:COE_HPD_Incident_Search_Octava")]
    public enum z1D_Original_Incident_IATType
    {
        
        /// <remarks/>
        Original,
        
        /// <remarks/>
        Duplicate,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:COE_HPD_Incident_Search_Octava")]
    public enum ProtocolType
    {
        
        /// <remarks/>
        AR,
        
        /// <remarks/>
        URL,
        
        /// <remarks/>
        Webservices,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Command Line")]
        CommandLine,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Plug-in")]
        Plugin,
        
        /// <remarks/>
        Other,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:COE_HPD_Incident_Search_Octava")]
    public enum Created_From_flagType
    {
        
        /// <remarks/>
        Incident,
        
        /// <remarks/>
        Request,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:COE_HPD_Incident_Search_Octava")]
    public enum z1D_NotifyIndGrpType
    {
        
        /// <remarks/>
        Individual,
        
        /// <remarks/>
        Group,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:COE_HPD_Incident_Search_Octava")]
    public enum Abydos_Notify_RecipientType
    {
        
        /// <remarks/>
        Requestor,
        
        /// <remarks/>
        Submitter,
        
        /// <remarks/>
        Supervisor,
        
        /// <remarks/>
        Sent,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:COE_HPD_Incident_Search_Octava")]
    public enum Override_GroupType
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Override Group Assignment")]
        OverrideGroupAssignment,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:COE_HPD_Incident_Search_Octava")]
    public enum TicketTypeType
    {
        
        /// <remarks/>
        Incident,
        
        /// <remarks/>
        Change,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Problem Investigation")]
        ProblemInvestigation,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Known Error")]
        KnownError,
        
        /// <remarks/>
        Knowledge,
        
        /// <remarks/>
        Task,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("CI Unavailability")]
        CIUnavailability,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Purchase Requisition")]
        PurchaseRequisition,
        
        /// <remarks/>
        Release,
        
        /// <remarks/>
        Activity,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:COE_HPD_Incident_Search_Octava")]
    public enum AccessModeType
    {
        
        /// <remarks/>
        Local,
        
        /// <remarks/>
        Remote,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:COE_HPD_Incident_Search_Octava")]
    public enum zD_GoalTypesType
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Request-Based")]
        RequestBased,
        
        /// <remarks/>
        Availability,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Event-Monitoring")]
        EventMonitoring,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Performance-Monitoring")]
        PerformanceMonitoring,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:COE_HPD_Incident_Search_Octava")]
    public enum CategoryType
    {
        
        /// <remarks/>
        Bug,
        
        /// <remarks/>
        Enhancement,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:COE_HPD_Incident_Search_Octava")]
    public enum SLM_StatusType
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("No Service Target Assigned")]
        NoServiceTargetAssigned,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Within the Service Target")]
        WithintheServiceTarget,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Service Target Warning")]
        ServiceTargetWarning,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Service Targets Breached")]
        ServiceTargetsBreached,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("All Service Targets Breached")]
        AllServiceTargetsBreached,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:COE_HPD_Incident_Search_Octava")]
    public enum InfrastructureEventTypeType
    {
        
        /// <remarks/>
        Event,
        
        /// <remarks/>
        Causal,
        
        /// <remarks/>
        Impact,
        
        /// <remarks/>
        None,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:COE_HPD_Incident_Search_Octava")]
    public enum z1D_CommunicationSourceType
    {
        
        /// <remarks/>
        Email,
        
        /// <remarks/>
        Fax,
        
        /// <remarks/>
        Phone,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Voice Mail")]
        VoiceMail,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Walk In")]
        WalkIn,
        
        /// <remarks/>
        Pager,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("System Assignment")]
        SystemAssignment,
        
        /// <remarks/>
        Web,
        
        /// <remarks/>
        Other,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("BMC Impact Manager Event")]
        BMCImpactManagerEvent,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:COE_HPD_Incident_Search_Octava")]
    public enum z1G_TenancyModeType
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Multi-Tenancy")]
        MultiTenancy,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Single-Tenancy")]
        SingleTenancy,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="New_Get_Operation_0", WrapperNamespace="urn:COE_HPD_Incident_Search_Octava", IsWrapped=true)]
    public partial class New_Get_Operation_0Request
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:COE_HPD_Incident_Search_Octava")]
        public CoE.Issues.Remedy.Watcher.RemedyServiceReference.AuthenticationInfo AuthenticationInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_HPD_Incident_Search_Octava", Order=0)]
        public string z1D_Template_Name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_HPD_Incident_Search_Octava", Order=1)]
        public string Last_Modified_Date;
        
        public New_Get_Operation_0Request()
        {
        }
        
        public New_Get_Operation_0Request(CoE.Issues.Remedy.Watcher.RemedyServiceReference.AuthenticationInfo AuthenticationInfo, string z1D_Template_Name, string Last_Modified_Date)
        {
            this.AuthenticationInfo = AuthenticationInfo;
            this.z1D_Template_Name = z1D_Template_Name;
            this.Last_Modified_Date = Last_Modified_Date;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="New_Get_Operation_0Response", WrapperNamespace="urn:COE_HPD_Incident_Search_Octava", IsWrapped=true)]
    public partial class New_Get_Operation_0Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_HPD_Incident_Search_Octava", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("getListValues")]
        public CoE.Issues.Remedy.Watcher.RemedyServiceReference.OutputMapping1GetListValues[] getListValues;
        
        public New_Get_Operation_0Response()
        {
        }
        
        public New_Get_Operation_0Response(CoE.Issues.Remedy.Watcher.RemedyServiceReference.OutputMapping1GetListValues[] getListValues)
        {
            this.getListValues = getListValues;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface New_Port_0PortTypeChannel : CoE.Issues.Remedy.Watcher.RemedyServiceReference.New_Port_0PortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class New_Port_0PortTypeClient : System.ServiceModel.ClientBase<CoE.Issues.Remedy.Watcher.RemedyServiceReference.New_Port_0PortType>, CoE.Issues.Remedy.Watcher.RemedyServiceReference.New_Port_0PortType
    {
        
        public New_Port_0PortTypeClient()
        {
        }
        
        public New_Port_0PortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public New_Port_0PortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public New_Port_0PortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public New_Port_0PortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CoE.Issues.Remedy.Watcher.RemedyServiceReference.New_Get_Operation_0Response CoE.Issues.Remedy.Watcher.RemedyServiceReference.New_Port_0PortType.New_Get_Operation_0(CoE.Issues.Remedy.Watcher.RemedyServiceReference.New_Get_Operation_0Request request)
        {
            return base.Channel.New_Get_Operation_0(request);
        }
        
        public CoE.Issues.Remedy.Watcher.RemedyServiceReference.OutputMapping1GetListValues[] New_Get_Operation_0(CoE.Issues.Remedy.Watcher.RemedyServiceReference.AuthenticationInfo AuthenticationInfo, string z1D_Template_Name, string Last_Modified_Date)
        {
            CoE.Issues.Remedy.Watcher.RemedyServiceReference.New_Get_Operation_0Request inValue = new CoE.Issues.Remedy.Watcher.RemedyServiceReference.New_Get_Operation_0Request();
            inValue.AuthenticationInfo = AuthenticationInfo;
            inValue.z1D_Template_Name = z1D_Template_Name;
            inValue.Last_Modified_Date = Last_Modified_Date;
            CoE.Issues.Remedy.Watcher.RemedyServiceReference.New_Get_Operation_0Response retVal = ((CoE.Issues.Remedy.Watcher.RemedyServiceReference.New_Port_0PortType)(this)).New_Get_Operation_0(inValue);
            return retVal.getListValues;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CoE.Issues.Remedy.Watcher.RemedyServiceReference.New_Get_Operation_0Response> CoE.Issues.Remedy.Watcher.RemedyServiceReference.New_Port_0PortType.New_Get_Operation_0Async(CoE.Issues.Remedy.Watcher.RemedyServiceReference.New_Get_Operation_0Request request)
        {
            return base.Channel.New_Get_Operation_0Async(request);
        }
        
        public System.Threading.Tasks.Task<CoE.Issues.Remedy.Watcher.RemedyServiceReference.New_Get_Operation_0Response> New_Get_Operation_0Async(CoE.Issues.Remedy.Watcher.RemedyServiceReference.AuthenticationInfo AuthenticationInfo, string z1D_Template_Name, string Last_Modified_Date)
        {
            CoE.Issues.Remedy.Watcher.RemedyServiceReference.New_Get_Operation_0Request inValue = new CoE.Issues.Remedy.Watcher.RemedyServiceReference.New_Get_Operation_0Request();
            inValue.AuthenticationInfo = AuthenticationInfo;
            inValue.z1D_Template_Name = z1D_Template_Name;
            inValue.Last_Modified_Date = Last_Modified_Date;
            return ((CoE.Issues.Remedy.Watcher.RemedyServiceReference.New_Port_0PortType)(this)).New_Get_Operation_0Async(inValue);
        }
    }
}
