// <auto-generated />
using CoE.Issues.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace CoE.Issues.Core.Migrations
{
    [DbContext(typeof(IssueContext))]
    partial class IssueContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("CoE.Issues.Core.Data.Issue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AssigneeEmail");

                    b.Property<string>("AssigneeGroup");

                    b.Property<int?>("AssigneeId");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Description");

                    b.Property<string>("ReferenceId");

                    b.Property<string>("RemedyStatus");

                    b.Property<string>("RequestorName");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<Guid>("Uid");

                    b.HasKey("Id");

                    b.ToTable("Issues");
                });

            modelBuilder.Entity("CoE.Issues.Core.Data.Stakeholder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("IssueId");

                    b.Property<int>("PersonId");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.HasIndex("IssueId");

                    b.ToTable("Stakeholder");
                });

            modelBuilder.Entity("CoE.Issues.Core.Data.Stakeholder", b =>
                {
                    b.HasOne("CoE.Issues.Core.Data.Issue")
                        .WithMany("Stakeholders")
                        .HasForeignKey("IssueId");
                });
#pragma warning restore 612, 618
        }
    }
}
