# How to build this image:
# From the parent folder enter:
# docker image build -t octava/nginx:dev-stretch -f docker/Dockerfile.nginx.dev-stretch ./docker/nginx
#
# And to push to the CoE Azure Repo (requires credentials):
# docker tag octava/nginx:dev-stretch coeoctava.azurecr.io/nginx:dev-stretch
# docker tag octava/nginx:dev-stretch coeoctava.azurecr.io/nginx:dev-latest
# docker push coeoctava.azurecr.io/nginx:dev-stretch
# docker push coeoctava.azurecr.io/nginx:dev-latest

FROM nginx:1.13

LABEL authors = "Dan Chenier (daniel.chenier@edmonton.ca)"

COPY octava.conf /etc/nginx/conf.d/default.conf