# How to build this image:
# From the parent folder enter:
# docker image build -t octava/initiatives-vue:dev -f docker/Dockerfile.initiatives-vue.dev-stretch .
#
# And to push to the CoE Azure Repo (requires credentials):
# docker tag octava/initiatives-vue:dev coeoctava.azurecr.io/initiatives-vue:dev
# docker tag octava/initiatives-vue:dev coeoctava.azurecr.io/initiatives-vue:dev-stretch
# docker tag octava/initiatives-vue:dev coeoctava.azurecr.io/initiatives-vue:dev-latest
# docker push coeoctava.azurecr.io/initiatives-vue:dev
# docker push coeoctava.azurecr.io/initiatives-vue:dev-stretch
# docker push coeoctava.azurecr.io/initiatives-vue:dev-latest

FROM node:9.10 AS initiatives-web

VOLUME /usr/src/coe-initiatives/

WORKDIR /usr/src/coe-initiatives/
ADD ./plugins/ideas .
ADD docker/initiatives-vue/entrypoint.sh /coe-entrypoint.sh
RUN npm install

CMD /bin/bash /coe-entrypoint.sh
