# How to build this image:
# From the parent folder enter:
# docker image build -t octava/initiatives-remedy-watcher:stretch -f docker/Dockerfile.initiatives-remedy-watcher .
#
# And to push to the CoE Azure Repo (requires credentials):
# docker tag octava/initiatives-remedy-watcher:stretch coeoctava.azurecr.io/initiatives-remedy-watcher:stretch
# docker tag octava/initiatives-remedy-watcher:stretch coeoctava.azurecr.io/initiatives-remedy-watcher:latest
# docker push coeoctava.azurecr.io/initiatives-remedy-watcher:stretch
# docker push coeoctava.azurecr.io/initiatives-remedy-watcher:latest

FROM microsoft/dotnet:2.0-sdk-stretch AS builder
#ARG Configuration=Debug
WORKDIR /usr/src/coe-initiatives-remedy-watcher
COPY ./server .
WORKDIR /usr/src/coe-initiatives-remedy-watcher/ideas-integration-remedy/ideas-integration-remedy-watcher
RUN dotnet publish

FROM microsoft/dotnet:2.0-runtime-stretch
ARG Configuration=Debug
WORKDIR /app
COPY --from=builder /usr/src/coe-initiatives-remedy-watcher/ideas-integration-remedy/ideas-integration-remedy-watcher/bin/$Configuration/netcoreapp2.0/publish  .

ENTRYPOINT ["dotnet"]
CMD ["ideas-integration-remedy-watcher.dll"]
