# How to build this image:
# From the parent folder enter:
# docker image build -t coeoctava.azurecr.io/initiatives-vue:dev -t coeoctava.azurecr.io/initiatives-vue:dev-stretch -t coeoctava.azurecr.io/initiatives-vue:dev-latest -f docker/Dockerfile.initiatives-vue.dev-stretch ./plugins/ideas
#
# And to push to the CoE Azure Repo (requires credentials):
# docker push coeoctava.azurecr.io/initiatives-vue:dev
# docker push coeoctava.azurecr.io/initiatives-vue:dev-stretch
# docker push coeoctava.azurecr.io/initiatives-vue:dev-latest

FROM node:9.10 AS initiatives-web

VOLUME /app

WORKDIR /app
ADD . .
RUN npm install

CMD npm rebuild node-sass & npm run dev
