# How to build this image:
# From the parent folder enter:
# docker image build -t coeoctava.azurecr.io/initiatives-webapi:dev-latest -f docker/Dockerfile.initiatives-server.dev-stretch ./server
#
# And to push to the CoE Azure Repo (requires credentials):
# docker tag coeoctava.azurecr.io/initiatives-webapi:dev-latest coeoctava.azurecr.io/initiatives-webapi:dev-stretch
# docker push coeoctava.azurecr.io/initiatives-webapi:dev-stretch
# docker push coeoctava.azurecr.io/initiatives-webapi:dev-latest

# developing ASP.NET Core with Docker how to setup:
# https://www.natemcmaster.com/blog/2017/11/13/dotnet-watch-and-docker/

FROM microsoft/aspnetcore-build:2.0-stretch AS initiatives-server
ARG Configuration=Debug

# Required inside Docker, otherwise file-change events may not trigger
ENV DOTNET_USE_POLLING_FILE_WATCHER 1

VOLUME /app

WORKDIR /app
COPY ./server/shared-kernel ./shared-kernel
COPY ./server/ideas-core/ideas-core ./ideas-core/ideas-core
COPY ./server/ideas-server/ideas-server ./ideas-server/ideas-server
WORKDIR /app/ideas-server/ideas-server

RUN dotnet restore
RUN dotnet build

ENTRYPOINT dotnet run urls=http://0.0.0.0:5000