# How to build this image:
# From the parent folder enter:
# docker image build -t coeoctava.azurecr.io/nginx:dev-latest -t coeoctava.azurecr.io/nginx:dev-latest -f docker/Dockerfile.nginx.dev-stretch ./
#
# And to push to the CoE Azure Repo (requires credentials):
# docker push coeoctava.azurecr.io/nginx:dev-stretch
# docker push coeoctava.azurecr.io/nginx:dev-latest

FROM nginx:1.13

LABEL authors = "Dan Chenier (daniel.chenier@edmonton.ca)"

COPY ./docker/nginx/octava.conf /etc/nginx/conf.d/default.conf
