//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoE.Ideas.Remedy.RemedyServiceReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS_Octava", ConfigurationName="CoE.Ideas.Remedy.RemedyServiceReference.New_Port_0PortType")]
    public interface New_Port_0PortType
    {
        
        // CODEGEN: Generating message contract since message New_Create_Operation_0Request has headers
        [System.ServiceModel.OperationContractAttribute(Action="urn:COE_WOI_WorkOrderInterface_WS_Octava/New_Create_Operation_0", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        CoE.Ideas.Remedy.RemedyServiceReference.New_Create_Operation_0Response New_Create_Operation_0(CoE.Ideas.Remedy.RemedyServiceReference.New_Create_Operation_0Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:COE_WOI_WorkOrderInterface_WS_Octava/New_Create_Operation_0", ReplyAction="*")]
        System.Threading.Tasks.Task<CoE.Ideas.Remedy.RemedyServiceReference.New_Create_Operation_0Response> New_Create_Operation_0Async(CoE.Ideas.Remedy.RemedyServiceReference.New_Create_Operation_0Request request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS_Octava")]
    public partial class AuthenticationInfo
    {
        
        private string userNameField;
        
        private string passwordField;
        
        private string authenticationField;
        
        private string localeField;
        
        private string timeZoneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string userName
        {
            get
            {
                return this.userNameField;
            }
            set
            {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string authentication
        {
            get
            {
                return this.authenticationField;
            }
            set
            {
                this.authenticationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string locale
        {
            get
            {
                return this.localeField;
            }
            set
            {
                this.localeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string timeZone
        {
            get
            {
                return this.timeZoneField;
            }
            set
            {
                this.timeZoneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS_Octava")]
    public enum Requested_ForType
    {
        
        /// <remarks/>
        Individual,
        
        /// <remarks/>
        Organization,
        
        /// <remarks/>
        Department,
        
        /// <remarks/>
        Company,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="New_Create_Operation_0", WrapperNamespace="urn:COE_WOI_WorkOrderInterface_WS_Octava", IsWrapped=true)]
    public partial class New_Create_Operation_0Request
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS_Octava")]
        public CoE.Ideas.Remedy.RemedyServiceReference.AuthenticationInfo AuthenticationInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS_Octava", Order=0)]
        public string Customer_Company;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS_Octava", Order=1)]
        public string Customer_Login_ID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS_Octava", Order=2)]
        public string z1D_Action;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS_Octava", Order=3)]
        public string Summary;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS_Octava", Order=4)]
        public string Description;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS_Octava", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<Requested_ForType> Requested_For;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS_Octava", Order=6)]
        public string Location_Company;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS_Octava", Order=7)]
        public string Work_Order_Template_Used;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS_Octava", Order=8)]
        public string TemplateName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS_Octava", Order=9)]
        [System.ComponentModel.DefaultValueAttribute("Categorization_Tier_1")]
        public string Categorization_Tier_1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS_Octava", Order=10)]
        public string Categorization_Tier_2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS_Octava", Order=11)]
        public string Categorization_Tier_3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS_Octava", Order=12)]
        public string TemplateID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS_Octava", Order=13)]
        public string Customer_First_Name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS_Octava", Order=14)]
        public string Customer_Last_Name;
        
        public New_Create_Operation_0Request()
        {
        }
        
        public New_Create_Operation_0Request(
                    CoE.Ideas.Remedy.RemedyServiceReference.AuthenticationInfo AuthenticationInfo, 
                    string Customer_Company, 
                    string Customer_Login_ID, 
                    string z1D_Action, 
                    string Summary, 
                    string Description, 
                    System.Nullable<Requested_ForType> Requested_For, 
                    string Location_Company, 
                    string Work_Order_Template_Used, 
                    string TemplateName, 
                    string Categorization_Tier_1, 
                    string Categorization_Tier_2, 
                    string Categorization_Tier_3, 
                    string TemplateID, 
                    string Customer_First_Name, 
                    string Customer_Last_Name)
        {
            this.AuthenticationInfo = AuthenticationInfo;
            this.Customer_Company = Customer_Company;
            this.Customer_Login_ID = Customer_Login_ID;
            this.z1D_Action = z1D_Action;
            this.Summary = Summary;
            this.Description = Description;
            this.Requested_For = Requested_For;
            this.Location_Company = Location_Company;
            this.Work_Order_Template_Used = Work_Order_Template_Used;
            this.TemplateName = TemplateName;
            this.Categorization_Tier_1 = Categorization_Tier_1;
            this.Categorization_Tier_2 = Categorization_Tier_2;
            this.Categorization_Tier_3 = Categorization_Tier_3;
            this.TemplateID = TemplateID;
            this.Customer_First_Name = Customer_First_Name;
            this.Customer_Last_Name = Customer_Last_Name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="New_Create_Operation_0Response", WrapperNamespace="urn:COE_WOI_WorkOrderInterface_WS_Octava", IsWrapped=true)]
    public partial class New_Create_Operation_0Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS_Octava", Order=0)]
        public string InstanceId;
        
        public New_Create_Operation_0Response()
        {
        }
        
        public New_Create_Operation_0Response(string InstanceId)
        {
            this.InstanceId = InstanceId;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface New_Port_0PortTypeChannel : CoE.Ideas.Remedy.RemedyServiceReference.New_Port_0PortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class New_Port_0PortTypeClient : System.ServiceModel.ClientBase<CoE.Ideas.Remedy.RemedyServiceReference.New_Port_0PortType>, CoE.Ideas.Remedy.RemedyServiceReference.New_Port_0PortType
    {
        
        public New_Port_0PortTypeClient()
        {
        }
        
        public New_Port_0PortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public New_Port_0PortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public New_Port_0PortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public New_Port_0PortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CoE.Ideas.Remedy.RemedyServiceReference.New_Create_Operation_0Response CoE.Ideas.Remedy.RemedyServiceReference.New_Port_0PortType.New_Create_Operation_0(CoE.Ideas.Remedy.RemedyServiceReference.New_Create_Operation_0Request request)
        {
            return base.Channel.New_Create_Operation_0(request);
        }
        
        public string New_Create_Operation_0(
                    CoE.Ideas.Remedy.RemedyServiceReference.AuthenticationInfo AuthenticationInfo, 
                    string Customer_Company, 
                    string Customer_Login_ID, 
                    string z1D_Action, 
                    string Summary, 
                    string Description, 
                    System.Nullable<Requested_ForType> Requested_For, 
                    string Location_Company, 
                    string Work_Order_Template_Used, 
                    string TemplateName, 
                    string Categorization_Tier_1, 
                    string Categorization_Tier_2, 
                    string Categorization_Tier_3, 
                    string TemplateID, 
                    string Customer_First_Name, 
                    string Customer_Last_Name)
        {
            CoE.Ideas.Remedy.RemedyServiceReference.New_Create_Operation_0Request inValue = new CoE.Ideas.Remedy.RemedyServiceReference.New_Create_Operation_0Request();
            inValue.AuthenticationInfo = AuthenticationInfo;
            inValue.Customer_Company = Customer_Company;
            inValue.Customer_Login_ID = Customer_Login_ID;
            inValue.z1D_Action = z1D_Action;
            inValue.Summary = Summary;
            inValue.Description = Description;
            inValue.Requested_For = Requested_For;
            inValue.Location_Company = Location_Company;
            inValue.Work_Order_Template_Used = Work_Order_Template_Used;
            inValue.TemplateName = TemplateName;
            inValue.Categorization_Tier_1 = Categorization_Tier_1;
            inValue.Categorization_Tier_2 = Categorization_Tier_2;
            inValue.Categorization_Tier_3 = Categorization_Tier_3;
            inValue.TemplateID = TemplateID;
            inValue.Customer_First_Name = Customer_First_Name;
            inValue.Customer_Last_Name = Customer_Last_Name;
            CoE.Ideas.Remedy.RemedyServiceReference.New_Create_Operation_0Response retVal = ((CoE.Ideas.Remedy.RemedyServiceReference.New_Port_0PortType)(this)).New_Create_Operation_0(inValue);
            return retVal.InstanceId;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CoE.Ideas.Remedy.RemedyServiceReference.New_Create_Operation_0Response> CoE.Ideas.Remedy.RemedyServiceReference.New_Port_0PortType.New_Create_Operation_0Async(CoE.Ideas.Remedy.RemedyServiceReference.New_Create_Operation_0Request request)
        {
            return base.Channel.New_Create_Operation_0Async(request);
        }
        
        public System.Threading.Tasks.Task<CoE.Ideas.Remedy.RemedyServiceReference.New_Create_Operation_0Response> New_Create_Operation_0Async(
                    CoE.Ideas.Remedy.RemedyServiceReference.AuthenticationInfo AuthenticationInfo, 
                    string Customer_Company, 
                    string Customer_Login_ID, 
                    string z1D_Action, 
                    string Summary, 
                    string Description, 
                    System.Nullable<Requested_ForType> Requested_For, 
                    string Location_Company, 
                    string Work_Order_Template_Used, 
                    string TemplateName, 
                    string Categorization_Tier_1, 
                    string Categorization_Tier_2, 
                    string Categorization_Tier_3, 
                    string TemplateID, 
                    string Customer_First_Name, 
                    string Customer_Last_Name)
        {
            CoE.Ideas.Remedy.RemedyServiceReference.New_Create_Operation_0Request inValue = new CoE.Ideas.Remedy.RemedyServiceReference.New_Create_Operation_0Request();
            inValue.AuthenticationInfo = AuthenticationInfo;
            inValue.Customer_Company = Customer_Company;
            inValue.Customer_Login_ID = Customer_Login_ID;
            inValue.z1D_Action = z1D_Action;
            inValue.Summary = Summary;
            inValue.Description = Description;
            inValue.Requested_For = Requested_For;
            inValue.Location_Company = Location_Company;
            inValue.Work_Order_Template_Used = Work_Order_Template_Used;
            inValue.TemplateName = TemplateName;
            inValue.Categorization_Tier_1 = Categorization_Tier_1;
            inValue.Categorization_Tier_2 = Categorization_Tier_2;
            inValue.Categorization_Tier_3 = Categorization_Tier_3;
            inValue.TemplateID = TemplateID;
            inValue.Customer_First_Name = Customer_First_Name;
            inValue.Customer_Last_Name = Customer_Last_Name;
            return ((CoE.Ideas.Remedy.RemedyServiceReference.New_Port_0PortType)(this)).New_Create_Operation_0Async(inValue);
        }
    }
}
