//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemedyServiceReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", ConfigurationName="RemedyServiceReference.New_Port_0PortType")]
    public interface New_Port_0PortType
    {
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:COE_WOI_WorkOrderInterface_WS/New_Create_Operation_0", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<RemedyServiceReference.New_Create_Operation_0Response> New_Create_Operation_0Async(RemedyServiceReference.New_Create_Operation_0Request request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS")]
    public partial class AuthenticationInfo
    {
        
        private string userNameField;
        
        private string passwordField;
        
        private string authenticationField;
        
        private string localeField;
        
        private string timeZoneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string userName
        {
            get
            {
                return this.userNameField;
            }
            set
            {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string authentication
        {
            get
            {
                return this.authenticationField;
            }
            set
            {
                this.authenticationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string locale
        {
            get
            {
                return this.localeField;
            }
            set
            {
                this.localeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string timeZone
        {
            get
            {
                return this.timeZoneField;
            }
            set
            {
                this.timeZoneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS")]
    public enum Set_Manager_usingType
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Auto Assign")]
        AutoAssign,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS")]
    public enum StatusType
    {
        
        /// <remarks/>
        Assigned,
        
        /// <remarks/>
        Pending,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Waiting Approval")]
        WaitingApproval,
        
        /// <remarks/>
        Planning,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("In Progress")]
        InProgress,
        
        /// <remarks/>
        Completed,
        
        /// <remarks/>
        Rejected,
        
        /// <remarks/>
        Cancelled,
        
        /// <remarks/>
        Closed,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS")]
    public enum SRWorkInfoTypeType
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Request Primary Attachment")]
        RequestPrimaryAttachment,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("WorkInfo created Before SR Submit")]
        WorkInfocreatedBeforeSRSubmit,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("WorkInfo created After SR Submit")]
        WorkInfocreatedAfterSRSubmit,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS")]
    public enum z1D_View_AccessType
    {
        
        /// <remarks/>
        Internal,
        
        /// <remarks/>
        Public,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS")]
    public enum Secure_Work_Log2Type
    {
        
        /// <remarks/>
        Yes,
        
        /// <remarks/>
        No,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS")]
    public enum Assignment_Accelerator_AssigneeType
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("My Default Group")]
        MyDefaultGroup,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("My Group List")]
        MyGroupList,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Favorite Group(s)")]
        FavoriteGroups,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Auto Assign")]
        AutoAssign,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Change Manager")]
        ChangeManager,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS")]
    public enum z1D_CommunicationSourceType
    {
        
        /// <remarks/>
        Email,
        
        /// <remarks/>
        Fax,
        
        /// <remarks/>
        Phone,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Voice Mail")]
        VoiceMail,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Walk In")]
        WalkIn,
        
        /// <remarks/>
        Pager,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("System Assignment")]
        SystemAssignment,
        
        /// <remarks/>
        Web,
        
        /// <remarks/>
        Other,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS")]
    public enum CreatedFromBackEndSynchWIType
    {
        
        /// <remarks/>
        Yes,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS")]
    public enum Status_ReasonType
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("No Longer Required")]
        NoLongerRequired,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Funding Not Available")]
        FundingNotAvailable,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("To Be Re-Scheduled")]
        ToBeReScheduled,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Resources Not Available")]
        ResourcesNotAvailable,
        
        /// <remarks/>
        Successful,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Successful with Issues")]
        SuccessfulwithIssues,
        
        /// <remarks/>
        Unsuccessful,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Backed Out")]
        BackedOut,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Final Review Complete")]
        FinalReviewComplete,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Final Review Required")]
        FinalReviewRequired,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Additional Coding Required")]
        AdditionalCodingRequired,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Insufficient Task Data")]
        InsufficientTaskData,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("In Verification")]
        InVerification,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("In Rollout")]
        InRollout,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Insufficient Change Data")]
        InsufficientChangeData,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Schedule Conflicts")]
        ScheduleConflicts,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("In Development")]
        InDevelopment,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("In Test")]
        InTest,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("In Build")]
        InBuild,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("In Rollback")]
        InRollback,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("In Documentation")]
        InDocumentation,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Vendor Purchase")]
        VendorPurchase,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Support Group Communication")]
        SupportGroupCommunication,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Task Review")]
        TaskReview,
        
        /// <remarks/>
        Miscellaneous,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Future Enhancement")]
        FutureEnhancement,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Manager Intervention")]
        ManagerIntervention,
        
        /// <remarks/>
        Accepted,
        
        /// <remarks/>
        Assigned,
        
        /// <remarks/>
        Built,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("On Hold")]
        OnHold,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Automatically Closed")]
        AutomaticallyClosed,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS")]
    public enum Work_Order_TypeType
    {
        
        /// <remarks/>
        Project,
        
        /// <remarks/>
        General,
        
        /// <remarks/>
        Release,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Asset Configuration")]
        AssetConfiguration,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Asset Management")]
        AssetManagement,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Asset Lease")]
        AssetLease,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Purchase Requisition")]
        PurchaseRequisition,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Asset Maintenance")]
        AssetMaintenance,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS")]
    public enum PriorityType
    {
        
        /// <remarks/>
        Critical,
        
        /// <remarks/>
        High,
        
        /// <remarks/>
        Medium,
        
        /// <remarks/>
        Low,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS")]
    public enum Created_From_flagType
    {
        
        /// <remarks/>
        Change,
        
        /// <remarks/>
        Request,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS")]
    public enum Contact_SensitivityType
    {
        
        /// <remarks/>
        Sensitive,
        
        /// <remarks/>
        Standard,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS")]
    public enum Add_Request_For_Type
    {
        
        /// <remarks/>
        Individual,
        
        /// <remarks/>
        Organization,
        
        /// <remarks/>
        Department,
        
        /// <remarks/>
        Company,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="New_Create_Operation_0", WrapperNamespace="urn:COE_WOI_WorkOrderInterface_WS", IsWrapped=true)]
    public partial class New_Create_Operation_0Request
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS")]
        public RemedyServiceReference.AuthenticationInfo AuthenticationInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=0)]
        public string WO_Type_Field_16_Label;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=1)]
        public string Customer_Login_ID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=2)]
        public string Submitter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=3)]
        public string CAB_Manager_Login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=4)]
        public string Assigned_To;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<Set_Manager_usingType> Set_Manager_using;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=6)]
        public RemedyServiceReference.StatusType Status;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=7)]
        public string Short_Description;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=8)]
        public string CustomRecordInstanceId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=9)]
        public string Request_Manager;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=10)]
        public int WO_Type_Field_25;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=11)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<SRWorkInfoTypeType> SRWorkInfoType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=12)]
        public string WO_Type_Field_21_Label;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=13)]
        public string WO_Type_Field_26_Label;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=14)]
        public string z1D_WorklogDetails;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=15)]
        public string WO_Type_Field_30;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=16)]
        public string WO_Type_Field_15;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=17)]
        public string WO_Type_Field_10_Label;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=18)]
        public string WO_Type_Field_10;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=19)]
        public string TemplateName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=20)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<z1D_View_AccessType> z1D_View_Access;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=21)]
        public string WO_Type_Field_20;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=22)]
        public string Schema_Name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=23)]
        public string LookupKeyword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=24)]
        public string WO_Type_Field_11_Label;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=25)]
        public string StatusString;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=26)]
        public string z2AF_Act_Attachment_2_attachmentName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=27)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] z2AF_Act_Attachment_2_attachmentData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=28)]
        public int z2AF_Act_Attachment_2_attachmentOrigSize;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=29)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="time")]
        public System.DateTime WO_Type_Field_50;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=30)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="time")]
        public System.DateTime WO_Type_Field_51;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=31)]
        public string WO_Type_Field_48_Label;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=32)]
        public string SRMSAOIGuid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=33)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<Secure_Work_Log2Type> Secure_Work_Log2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=34)]
        public string WO_Type_Field_17_Label;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=35)]
        public string Requested_By_Person_ID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=36)]
        public string WO_Type_Field_22_Label;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=37)]
        public int WO_Type_Field_26;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=38)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime WO_Type_Field_48;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=39)]
        public string Assignee_Groups;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=40)]
        [System.ComponentModel.DefaultValueAttribute("0")]
        public string DatasetId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=41)]
        public System.DateTime z1D_ActivityDate_tab;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=42)]
        public string WO_Type_Field_27_Label;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=43)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime WO_Type_Field_49;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=44)]
        public string Site;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=45)]
        public string WO_Type_Field_16;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=46)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<Secure_Work_Log2Type> Secure_Work_Log;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=47)]
        public string SRInstanceID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=48)]
        public string WO_Type_Field_12_Label;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=49)]
        public string WO_Type_Field_04_Label;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=50)]
        public string WO_Type_Field_05_Label;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=51)]
        public string CustomerFullName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=52)]
        public string WO_Type_Field_06_Label;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=53)]
        public string WO_Type_Field_07_Label;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=54)]
        public string WO_Type_Field_01_Label;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=55)]
        public string WO_Type_Field_02_Label;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=56)]
        public string WO_Type_Field_03_Label;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=57)]
        public string WO_Type_Field_08_Label;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=58)]
        public string WO_Type_Field_21;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=59)]
        public string WO_Type_Field_09_Label;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=60)]
        public string WO_Type_Field_49_Label;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=61)]
        public string z2AF_Act_Attachment_1_attachmentName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=62)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] z2AF_Act_Attachment_1_attachmentData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=63)]
        public int z2AF_Act_Attachment_1_attachmentOrigSize;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=64)]
        public string StatusReasonString;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=65)]
        public string WO_Type_Field_50_Label;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=66)]
        public string WO_Type_Field_51_Label;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=67)]
        public string InstanceId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=68)]
        public string WO_Type_Field_11;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=69)]
        public string Cost_Centre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=70)]
        public System.DateTime Scheduled_Start_Date;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=71)]
        public string SRMSRegistryInstanceID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=72)]
        public System.DateTime Actual_Start_Date;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=73)]
        public string z1D_ConfirmGroup;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=74)]
        public string Requestor_ID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=75)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<Assignment_Accelerator_AssigneeType> Assignment_Accelerator_Assignee;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=76)]
        public string WO_Type_Field_23_Label;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=77)]
        public string Requester_Support_Organization;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=78)]
        public string WO_Type_Field_28_Label;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=79)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<z1D_CommunicationSourceType> z1D_CommunicationSource;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=80)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<CreatedFromBackEndSynchWIType> CreatedFromBackEndSynchWI;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=81)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<Secure_Work_Log2Type> CreatedfromParentTemplate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=82)]
        [System.ComponentModel.DefaultValueAttribute("Headline field")]
        public string Headline;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=83)]
        public string z1D_Details;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=84)]
        public string z1D_Status_Reason;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=85)]
        public string WO_Type_Field_17;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=86)]
        public System.DateTime Scheduled_End_Date;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=87)]
        public string WO_Type_Field_13_Label;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=88)]
        public int WO_Type_Field_27;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=89)]
        public System.DateTime Actual_End_Date;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=90)]
        public string WO_Type_Field_18_Label;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=91)]
        public string WO_Type_Field_22;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=92)]
        public string Support_Organization;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=93)]
        public string Request_Assignee;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=94)]
        public string Support_Company;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=95)]
        public string Support_Group_Name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=96)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<Status_ReasonType> Status_Reason;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=97)]
        public string Detailed_Description;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=98)]
        public string WO_Type_Field_12;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=99)]
        public string z1D_Char10;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=100)]
        public string WO_Type_Field_24_Label;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=101)]
        public string Customer_Middle_Name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=102)]
        public string WorkOrder_ID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=103)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<Work_Order_TypeType> Work_Order_Type;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=104)]
        public string WO_Type_Field_29_Label;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=105)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<PriorityType> Priority;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=106)]
        public string Manufacturer__2_;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=107)]
        public string WO_Type_Field_23;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=108)]
        public string Product_Name__2_;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=109)]
        public string Product_Model_Version__2_;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=110)]
        public string WO_Type_Field_14_Label;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=111)]
        public string WO_Type_Field_18;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=112)]
        public string WO_Type_Field_28;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=113)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<Created_From_flagType> Created_From_flag;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=114)]
        public string z1D_Summary;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=115)]
        public string WO_Type_Field_19_Label;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=116)]
        public string zTmpEventGUID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=117)]
        public string Request_Manager_Company;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=118)]
        public string Product_Cat_Tier_3__2_;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=119)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<z1D_View_AccessType> View_Access;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=120)]
        [System.ComponentModel.DefaultValueAttribute("0")]
        public string ReconciliationIdentity;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=121)]
        public string Product_Cat_Tier_1_2_;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=122)]
        public string Product_Cat_Tier_2__2_;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=123)]
        public string Customer_Phone_Number;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=124)]
        public string Customer_Last_Name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=125)]
        public string Customer_Company;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=126)]
        public string Customer_Person_ID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=127)]
        public string Customer_First_Name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=128)]
        [System.Xml.Serialization.XmlElementAttribute("Customer_Internet_E-mail")]
        public string Customer_Internet_Email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=129)]
        public string WO_Type_Field_13;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=130)]
        public string Customer_Organization;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=131)]
        public string Customer_Department;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=132)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<Secure_Work_Log2Type> VIP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=133)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<Contact_SensitivityType> Contact_Sensitivity;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=134)]
        public string WO_Type_Field_25_Label;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=135)]
        public string WO_Type_Field_30_Label;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=136)]
        public string Last_Name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=137)]
        public string First_Name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=138)]
        public string Middle_Initial;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=139)]
        public string WO_Type_Field_02;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=140)]
        public string Organization;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=141)]
        public string WO_Type_Field_03;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=142)]
        public string WO_Type_Field_01;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=143)]
        public System.DateTime WO_Type_Field_06;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=144)]
        public string Manager_Support_Organization;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=145)]
        public System.DateTime WO_Type_Field_07;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=146)]
        public string Manager_Support_Group_Name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=147)]
        public string WO_Type_Field_04;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=148)]
        public string WO_Type_Field_05;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=149)]
        public string ClientLocale;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=150)]
        public int WO_Type_Field_08;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=151)]
        public string Summary;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=152)]
        public int WO_Type_Field_09;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=153)]
        public string Location_Company;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=154)]
        public string Custom_CFG_Form_InstanceId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=155)]
        public string z1D_Char01;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=156)]
        public string TemplateID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=157)]
        public int WO_Type_Field_24;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=158)]
        public string Phone_Number;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=159)]
        public string Categorization_Tier_1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=160)]
        [System.Xml.Serialization.XmlElementAttribute("Internet_E-mail")]
        public string Internet_Email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=161)]
        public string WO_Type_Field_15_Label;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=162)]
        public string WO_Type_Field_20_Label;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=163)]
        public string z1G_Global_AST_ProductionDataSetID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=164)]
        public int z1D_Permission_Group_ID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=165)]
        public string WorkOrder__EntryID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=166)]
        public string Chg_Location_Address;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=167)]
        public string WO_Type_Field_29;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=168)]
        public string Command;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=169)]
        public string Company;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=170)]
        public string Person_ID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=171)]
        public string Attachment_attachmentName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=172)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Attachment_attachmentData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=173)]
        public int Attachment_attachmentOrigSize;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=174)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<Add_Request_For_Type> Add_Request_For_;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=175)]
        public string Work_Order_Template_Instance_ID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=176)]
        public string Asset1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=177)]
        public string Asset3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=178)]
        public string Asset2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=179)]
        public string Asset5;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=180)]
        public string WO_Type_Field_19;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=181)]
        public string Asset4;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=182)]
        [System.ComponentModel.DefaultValueAttribute("CREATE")]
        public string z1D_Action;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=183)]
        public int z1D_Integer01;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=184)]
        public string WO_Type_Field_14;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=185)]
        public string Categorization_Tier_2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=186)]
        public string z1D_SRMCommand;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=187)]
        public string Categorization_Tier_3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=188)]
        public string Vendor_Assignee_Groups;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=189)]
        public string Region;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=190)]
        public int z1D_Integer02;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=191)]
        public int z1D_Integer03;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=192)]
        public string Site_Group;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=193)]
        public string Department;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=194)]
        public string z2AF_Act_Attachment_3_attachmentName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=195)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] z2AF_Act_Attachment_3_attachmentData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=196)]
        public int z2AF_Act_Attachment_3_attachmentOrigSize;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=197)]
        [System.ComponentModel.DefaultValueAttribute("$USER$")]
        public string RequesterLoginID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=198)]
        public string SRID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=199)]
        public string CI_Name;
        
        public New_Create_Operation_0Request()
        {
        }
        
        public New_Create_Operation_0Request(
                    RemedyServiceReference.AuthenticationInfo AuthenticationInfo, 
                    string WO_Type_Field_16_Label, 
                    string Customer_Login_ID, 
                    string Submitter, 
                    string CAB_Manager_Login, 
                    string Assigned_To, 
                    System.Nullable<Set_Manager_usingType> Set_Manager_using, 
                    RemedyServiceReference.StatusType Status, 
                    string Short_Description, 
                    string CustomRecordInstanceId, 
                    string Request_Manager, 
                    int WO_Type_Field_25, 
                    System.Nullable<SRWorkInfoTypeType> SRWorkInfoType, 
                    string WO_Type_Field_21_Label, 
                    string WO_Type_Field_26_Label, 
                    string z1D_WorklogDetails, 
                    string WO_Type_Field_30, 
                    string WO_Type_Field_15, 
                    string WO_Type_Field_10_Label, 
                    string WO_Type_Field_10, 
                    string TemplateName, 
                    System.Nullable<z1D_View_AccessType> z1D_View_Access, 
                    string WO_Type_Field_20, 
                    string Schema_Name, 
                    string LookupKeyword, 
                    string WO_Type_Field_11_Label, 
                    string StatusString, 
                    string z2AF_Act_Attachment_2_attachmentName, 
                    byte[] z2AF_Act_Attachment_2_attachmentData, 
                    int z2AF_Act_Attachment_2_attachmentOrigSize, 
                    System.DateTime WO_Type_Field_50, 
                    System.DateTime WO_Type_Field_51, 
                    string WO_Type_Field_48_Label, 
                    string SRMSAOIGuid, 
                    System.Nullable<Secure_Work_Log2Type> Secure_Work_Log2, 
                    string WO_Type_Field_17_Label, 
                    string Requested_By_Person_ID, 
                    string WO_Type_Field_22_Label, 
                    int WO_Type_Field_26, 
                    System.DateTime WO_Type_Field_48, 
                    string Assignee_Groups, 
                    string DatasetId, 
                    System.DateTime z1D_ActivityDate_tab, 
                    string WO_Type_Field_27_Label, 
                    System.DateTime WO_Type_Field_49, 
                    string Site, 
                    string WO_Type_Field_16, 
                    System.Nullable<Secure_Work_Log2Type> Secure_Work_Log, 
                    string SRInstanceID, 
                    string WO_Type_Field_12_Label, 
                    string WO_Type_Field_04_Label, 
                    string WO_Type_Field_05_Label, 
                    string CustomerFullName, 
                    string WO_Type_Field_06_Label, 
                    string WO_Type_Field_07_Label, 
                    string WO_Type_Field_01_Label, 
                    string WO_Type_Field_02_Label, 
                    string WO_Type_Field_03_Label, 
                    string WO_Type_Field_08_Label, 
                    string WO_Type_Field_21, 
                    string WO_Type_Field_09_Label, 
                    string WO_Type_Field_49_Label, 
                    string z2AF_Act_Attachment_1_attachmentName, 
                    byte[] z2AF_Act_Attachment_1_attachmentData, 
                    int z2AF_Act_Attachment_1_attachmentOrigSize, 
                    string StatusReasonString, 
                    string WO_Type_Field_50_Label, 
                    string WO_Type_Field_51_Label, 
                    string InstanceId, 
                    string WO_Type_Field_11, 
                    string Cost_Centre, 
                    System.DateTime Scheduled_Start_Date, 
                    string SRMSRegistryInstanceID, 
                    System.DateTime Actual_Start_Date, 
                    string z1D_ConfirmGroup, 
                    string Requestor_ID, 
                    System.Nullable<Assignment_Accelerator_AssigneeType> Assignment_Accelerator_Assignee, 
                    string WO_Type_Field_23_Label, 
                    string Requester_Support_Organization, 
                    string WO_Type_Field_28_Label, 
                    System.Nullable<z1D_CommunicationSourceType> z1D_CommunicationSource, 
                    System.Nullable<CreatedFromBackEndSynchWIType> CreatedFromBackEndSynchWI, 
                    System.Nullable<Secure_Work_Log2Type> CreatedfromParentTemplate, 
                    string Headline, 
                    string z1D_Details, 
                    string z1D_Status_Reason, 
                    string WO_Type_Field_17, 
                    System.DateTime Scheduled_End_Date, 
                    string WO_Type_Field_13_Label, 
                    int WO_Type_Field_27, 
                    System.DateTime Actual_End_Date, 
                    string WO_Type_Field_18_Label, 
                    string WO_Type_Field_22, 
                    string Support_Organization, 
                    string Request_Assignee, 
                    string Support_Company, 
                    string Support_Group_Name, 
                    System.Nullable<Status_ReasonType> Status_Reason, 
                    string Detailed_Description, 
                    string WO_Type_Field_12, 
                    string z1D_Char10, 
                    string WO_Type_Field_24_Label, 
                    string Customer_Middle_Name, 
                    string WorkOrder_ID, 
                    System.Nullable<Work_Order_TypeType> Work_Order_Type, 
                    string WO_Type_Field_29_Label, 
                    System.Nullable<PriorityType> Priority, 
                    string Manufacturer__2_, 
                    string WO_Type_Field_23, 
                    string Product_Name__2_, 
                    string Product_Model_Version__2_, 
                    string WO_Type_Field_14_Label, 
                    string WO_Type_Field_18, 
                    string WO_Type_Field_28, 
                    System.Nullable<Created_From_flagType> Created_From_flag, 
                    string z1D_Summary, 
                    string WO_Type_Field_19_Label, 
                    string zTmpEventGUID, 
                    string Request_Manager_Company, 
                    string Product_Cat_Tier_3__2_, 
                    System.Nullable<z1D_View_AccessType> View_Access, 
                    string ReconciliationIdentity, 
                    string Product_Cat_Tier_1_2_, 
                    string Product_Cat_Tier_2__2_, 
                    string Customer_Phone_Number, 
                    string Customer_Last_Name, 
                    string Customer_Company, 
                    string Customer_Person_ID, 
                    string Customer_First_Name, 
                    string Customer_Internet_Email, 
                    string WO_Type_Field_13, 
                    string Customer_Organization, 
                    string Customer_Department, 
                    System.Nullable<Secure_Work_Log2Type> VIP, 
                    System.Nullable<Contact_SensitivityType> Contact_Sensitivity, 
                    string WO_Type_Field_25_Label, 
                    string WO_Type_Field_30_Label, 
                    string Last_Name, 
                    string First_Name, 
                    string Middle_Initial, 
                    string WO_Type_Field_02, 
                    string Organization, 
                    string WO_Type_Field_03, 
                    string WO_Type_Field_01, 
                    System.DateTime WO_Type_Field_06, 
                    string Manager_Support_Organization, 
                    System.DateTime WO_Type_Field_07, 
                    string Manager_Support_Group_Name, 
                    string WO_Type_Field_04, 
                    string WO_Type_Field_05, 
                    string ClientLocale, 
                    int WO_Type_Field_08, 
                    string Summary, 
                    int WO_Type_Field_09, 
                    string Location_Company, 
                    string Custom_CFG_Form_InstanceId, 
                    string z1D_Char01, 
                    string TemplateID, 
                    int WO_Type_Field_24, 
                    string Phone_Number, 
                    string Categorization_Tier_1, 
                    string Internet_Email, 
                    string WO_Type_Field_15_Label, 
                    string WO_Type_Field_20_Label, 
                    string z1G_Global_AST_ProductionDataSetID, 
                    int z1D_Permission_Group_ID, 
                    string WorkOrder__EntryID, 
                    string Chg_Location_Address, 
                    string WO_Type_Field_29, 
                    string Command, 
                    string Company, 
                    string Person_ID, 
                    string Attachment_attachmentName, 
                    byte[] Attachment_attachmentData, 
                    int Attachment_attachmentOrigSize, 
                    System.Nullable<Add_Request_For_Type> Add_Request_For_, 
                    string Work_Order_Template_Instance_ID, 
                    string Asset1, 
                    string Asset3, 
                    string Asset2, 
                    string Asset5, 
                    string WO_Type_Field_19, 
                    string Asset4, 
                    string z1D_Action, 
                    int z1D_Integer01, 
                    string WO_Type_Field_14, 
                    string Categorization_Tier_2, 
                    string z1D_SRMCommand, 
                    string Categorization_Tier_3, 
                    string Vendor_Assignee_Groups, 
                    string Region, 
                    int z1D_Integer02, 
                    int z1D_Integer03, 
                    string Site_Group, 
                    string Department, 
                    string z2AF_Act_Attachment_3_attachmentName, 
                    byte[] z2AF_Act_Attachment_3_attachmentData, 
                    int z2AF_Act_Attachment_3_attachmentOrigSize, 
                    string RequesterLoginID, 
                    string SRID, 
                    string CI_Name)
        {
            this.AuthenticationInfo = AuthenticationInfo;
            this.WO_Type_Field_16_Label = WO_Type_Field_16_Label;
            this.Customer_Login_ID = Customer_Login_ID;
            this.Submitter = Submitter;
            this.CAB_Manager_Login = CAB_Manager_Login;
            this.Assigned_To = Assigned_To;
            this.Set_Manager_using = Set_Manager_using;
            this.Status = Status;
            this.Short_Description = Short_Description;
            this.CustomRecordInstanceId = CustomRecordInstanceId;
            this.Request_Manager = Request_Manager;
            this.WO_Type_Field_25 = WO_Type_Field_25;
            this.SRWorkInfoType = SRWorkInfoType;
            this.WO_Type_Field_21_Label = WO_Type_Field_21_Label;
            this.WO_Type_Field_26_Label = WO_Type_Field_26_Label;
            this.z1D_WorklogDetails = z1D_WorklogDetails;
            this.WO_Type_Field_30 = WO_Type_Field_30;
            this.WO_Type_Field_15 = WO_Type_Field_15;
            this.WO_Type_Field_10_Label = WO_Type_Field_10_Label;
            this.WO_Type_Field_10 = WO_Type_Field_10;
            this.TemplateName = TemplateName;
            this.z1D_View_Access = z1D_View_Access;
            this.WO_Type_Field_20 = WO_Type_Field_20;
            this.Schema_Name = Schema_Name;
            this.LookupKeyword = LookupKeyword;
            this.WO_Type_Field_11_Label = WO_Type_Field_11_Label;
            this.StatusString = StatusString;
            this.z2AF_Act_Attachment_2_attachmentName = z2AF_Act_Attachment_2_attachmentName;
            this.z2AF_Act_Attachment_2_attachmentData = z2AF_Act_Attachment_2_attachmentData;
            this.z2AF_Act_Attachment_2_attachmentOrigSize = z2AF_Act_Attachment_2_attachmentOrigSize;
            this.WO_Type_Field_50 = WO_Type_Field_50;
            this.WO_Type_Field_51 = WO_Type_Field_51;
            this.WO_Type_Field_48_Label = WO_Type_Field_48_Label;
            this.SRMSAOIGuid = SRMSAOIGuid;
            this.Secure_Work_Log2 = Secure_Work_Log2;
            this.WO_Type_Field_17_Label = WO_Type_Field_17_Label;
            this.Requested_By_Person_ID = Requested_By_Person_ID;
            this.WO_Type_Field_22_Label = WO_Type_Field_22_Label;
            this.WO_Type_Field_26 = WO_Type_Field_26;
            this.WO_Type_Field_48 = WO_Type_Field_48;
            this.Assignee_Groups = Assignee_Groups;
            this.DatasetId = DatasetId;
            this.z1D_ActivityDate_tab = z1D_ActivityDate_tab;
            this.WO_Type_Field_27_Label = WO_Type_Field_27_Label;
            this.WO_Type_Field_49 = WO_Type_Field_49;
            this.Site = Site;
            this.WO_Type_Field_16 = WO_Type_Field_16;
            this.Secure_Work_Log = Secure_Work_Log;
            this.SRInstanceID = SRInstanceID;
            this.WO_Type_Field_12_Label = WO_Type_Field_12_Label;
            this.WO_Type_Field_04_Label = WO_Type_Field_04_Label;
            this.WO_Type_Field_05_Label = WO_Type_Field_05_Label;
            this.CustomerFullName = CustomerFullName;
            this.WO_Type_Field_06_Label = WO_Type_Field_06_Label;
            this.WO_Type_Field_07_Label = WO_Type_Field_07_Label;
            this.WO_Type_Field_01_Label = WO_Type_Field_01_Label;
            this.WO_Type_Field_02_Label = WO_Type_Field_02_Label;
            this.WO_Type_Field_03_Label = WO_Type_Field_03_Label;
            this.WO_Type_Field_08_Label = WO_Type_Field_08_Label;
            this.WO_Type_Field_21 = WO_Type_Field_21;
            this.WO_Type_Field_09_Label = WO_Type_Field_09_Label;
            this.WO_Type_Field_49_Label = WO_Type_Field_49_Label;
            this.z2AF_Act_Attachment_1_attachmentName = z2AF_Act_Attachment_1_attachmentName;
            this.z2AF_Act_Attachment_1_attachmentData = z2AF_Act_Attachment_1_attachmentData;
            this.z2AF_Act_Attachment_1_attachmentOrigSize = z2AF_Act_Attachment_1_attachmentOrigSize;
            this.StatusReasonString = StatusReasonString;
            this.WO_Type_Field_50_Label = WO_Type_Field_50_Label;
            this.WO_Type_Field_51_Label = WO_Type_Field_51_Label;
            this.InstanceId = InstanceId;
            this.WO_Type_Field_11 = WO_Type_Field_11;
            this.Cost_Centre = Cost_Centre;
            this.Scheduled_Start_Date = Scheduled_Start_Date;
            this.SRMSRegistryInstanceID = SRMSRegistryInstanceID;
            this.Actual_Start_Date = Actual_Start_Date;
            this.z1D_ConfirmGroup = z1D_ConfirmGroup;
            this.Requestor_ID = Requestor_ID;
            this.Assignment_Accelerator_Assignee = Assignment_Accelerator_Assignee;
            this.WO_Type_Field_23_Label = WO_Type_Field_23_Label;
            this.Requester_Support_Organization = Requester_Support_Organization;
            this.WO_Type_Field_28_Label = WO_Type_Field_28_Label;
            this.z1D_CommunicationSource = z1D_CommunicationSource;
            this.CreatedFromBackEndSynchWI = CreatedFromBackEndSynchWI;
            this.CreatedfromParentTemplate = CreatedfromParentTemplate;
            this.Headline = Headline;
            this.z1D_Details = z1D_Details;
            this.z1D_Status_Reason = z1D_Status_Reason;
            this.WO_Type_Field_17 = WO_Type_Field_17;
            this.Scheduled_End_Date = Scheduled_End_Date;
            this.WO_Type_Field_13_Label = WO_Type_Field_13_Label;
            this.WO_Type_Field_27 = WO_Type_Field_27;
            this.Actual_End_Date = Actual_End_Date;
            this.WO_Type_Field_18_Label = WO_Type_Field_18_Label;
            this.WO_Type_Field_22 = WO_Type_Field_22;
            this.Support_Organization = Support_Organization;
            this.Request_Assignee = Request_Assignee;
            this.Support_Company = Support_Company;
            this.Support_Group_Name = Support_Group_Name;
            this.Status_Reason = Status_Reason;
            this.Detailed_Description = Detailed_Description;
            this.WO_Type_Field_12 = WO_Type_Field_12;
            this.z1D_Char10 = z1D_Char10;
            this.WO_Type_Field_24_Label = WO_Type_Field_24_Label;
            this.Customer_Middle_Name = Customer_Middle_Name;
            this.WorkOrder_ID = WorkOrder_ID;
            this.Work_Order_Type = Work_Order_Type;
            this.WO_Type_Field_29_Label = WO_Type_Field_29_Label;
            this.Priority = Priority;
            this.Manufacturer__2_ = Manufacturer__2_;
            this.WO_Type_Field_23 = WO_Type_Field_23;
            this.Product_Name__2_ = Product_Name__2_;
            this.Product_Model_Version__2_ = Product_Model_Version__2_;
            this.WO_Type_Field_14_Label = WO_Type_Field_14_Label;
            this.WO_Type_Field_18 = WO_Type_Field_18;
            this.WO_Type_Field_28 = WO_Type_Field_28;
            this.Created_From_flag = Created_From_flag;
            this.z1D_Summary = z1D_Summary;
            this.WO_Type_Field_19_Label = WO_Type_Field_19_Label;
            this.zTmpEventGUID = zTmpEventGUID;
            this.Request_Manager_Company = Request_Manager_Company;
            this.Product_Cat_Tier_3__2_ = Product_Cat_Tier_3__2_;
            this.View_Access = View_Access;
            this.ReconciliationIdentity = ReconciliationIdentity;
            this.Product_Cat_Tier_1_2_ = Product_Cat_Tier_1_2_;
            this.Product_Cat_Tier_2__2_ = Product_Cat_Tier_2__2_;
            this.Customer_Phone_Number = Customer_Phone_Number;
            this.Customer_Last_Name = Customer_Last_Name;
            this.Customer_Company = Customer_Company;
            this.Customer_Person_ID = Customer_Person_ID;
            this.Customer_First_Name = Customer_First_Name;
            this.Customer_Internet_Email = Customer_Internet_Email;
            this.WO_Type_Field_13 = WO_Type_Field_13;
            this.Customer_Organization = Customer_Organization;
            this.Customer_Department = Customer_Department;
            this.VIP = VIP;
            this.Contact_Sensitivity = Contact_Sensitivity;
            this.WO_Type_Field_25_Label = WO_Type_Field_25_Label;
            this.WO_Type_Field_30_Label = WO_Type_Field_30_Label;
            this.Last_Name = Last_Name;
            this.First_Name = First_Name;
            this.Middle_Initial = Middle_Initial;
            this.WO_Type_Field_02 = WO_Type_Field_02;
            this.Organization = Organization;
            this.WO_Type_Field_03 = WO_Type_Field_03;
            this.WO_Type_Field_01 = WO_Type_Field_01;
            this.WO_Type_Field_06 = WO_Type_Field_06;
            this.Manager_Support_Organization = Manager_Support_Organization;
            this.WO_Type_Field_07 = WO_Type_Field_07;
            this.Manager_Support_Group_Name = Manager_Support_Group_Name;
            this.WO_Type_Field_04 = WO_Type_Field_04;
            this.WO_Type_Field_05 = WO_Type_Field_05;
            this.ClientLocale = ClientLocale;
            this.WO_Type_Field_08 = WO_Type_Field_08;
            this.Summary = Summary;
            this.WO_Type_Field_09 = WO_Type_Field_09;
            this.Location_Company = Location_Company;
            this.Custom_CFG_Form_InstanceId = Custom_CFG_Form_InstanceId;
            this.z1D_Char01 = z1D_Char01;
            this.TemplateID = TemplateID;
            this.WO_Type_Field_24 = WO_Type_Field_24;
            this.Phone_Number = Phone_Number;
            this.Categorization_Tier_1 = Categorization_Tier_1;
            this.Internet_Email = Internet_Email;
            this.WO_Type_Field_15_Label = WO_Type_Field_15_Label;
            this.WO_Type_Field_20_Label = WO_Type_Field_20_Label;
            this.z1G_Global_AST_ProductionDataSetID = z1G_Global_AST_ProductionDataSetID;
            this.z1D_Permission_Group_ID = z1D_Permission_Group_ID;
            this.WorkOrder__EntryID = WorkOrder__EntryID;
            this.Chg_Location_Address = Chg_Location_Address;
            this.WO_Type_Field_29 = WO_Type_Field_29;
            this.Command = Command;
            this.Company = Company;
            this.Person_ID = Person_ID;
            this.Attachment_attachmentName = Attachment_attachmentName;
            this.Attachment_attachmentData = Attachment_attachmentData;
            this.Attachment_attachmentOrigSize = Attachment_attachmentOrigSize;
            this.Add_Request_For_ = Add_Request_For_;
            this.Work_Order_Template_Instance_ID = Work_Order_Template_Instance_ID;
            this.Asset1 = Asset1;
            this.Asset3 = Asset3;
            this.Asset2 = Asset2;
            this.Asset5 = Asset5;
            this.WO_Type_Field_19 = WO_Type_Field_19;
            this.Asset4 = Asset4;
            this.z1D_Action = z1D_Action;
            this.z1D_Integer01 = z1D_Integer01;
            this.WO_Type_Field_14 = WO_Type_Field_14;
            this.Categorization_Tier_2 = Categorization_Tier_2;
            this.z1D_SRMCommand = z1D_SRMCommand;
            this.Categorization_Tier_3 = Categorization_Tier_3;
            this.Vendor_Assignee_Groups = Vendor_Assignee_Groups;
            this.Region = Region;
            this.z1D_Integer02 = z1D_Integer02;
            this.z1D_Integer03 = z1D_Integer03;
            this.Site_Group = Site_Group;
            this.Department = Department;
            this.z2AF_Act_Attachment_3_attachmentName = z2AF_Act_Attachment_3_attachmentName;
            this.z2AF_Act_Attachment_3_attachmentData = z2AF_Act_Attachment_3_attachmentData;
            this.z2AF_Act_Attachment_3_attachmentOrigSize = z2AF_Act_Attachment_3_attachmentOrigSize;
            this.RequesterLoginID = RequesterLoginID;
            this.SRID = SRID;
            this.CI_Name = CI_Name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="New_Create_Operation_0Response", WrapperNamespace="urn:COE_WOI_WorkOrderInterface_WS", IsWrapped=true)]
    public partial class New_Create_Operation_0Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=0)]
        public string InstanceId;
        
        public New_Create_Operation_0Response()
        {
        }
        
        public New_Create_Operation_0Response(string InstanceId)
        {
            this.InstanceId = InstanceId;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public interface New_Port_0PortTypeChannel : RemedyServiceReference.New_Port_0PortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public partial class New_Port_0PortTypeClient : System.ServiceModel.ClientBase<RemedyServiceReference.New_Port_0PortType>, RemedyServiceReference.New_Port_0PortType
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public New_Port_0PortTypeClient() : 
                base(New_Port_0PortTypeClient.GetDefaultBinding(), New_Port_0PortTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.New_Port_0Soap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public New_Port_0PortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(New_Port_0PortTypeClient.GetBindingForEndpoint(endpointConfiguration), New_Port_0PortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public New_Port_0PortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(New_Port_0PortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public New_Port_0PortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(New_Port_0PortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public New_Port_0PortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<RemedyServiceReference.New_Create_Operation_0Response> New_Create_Operation_0Async(RemedyServiceReference.New_Create_Operation_0Request request)
        {
            return base.Channel.New_Create_Operation_0Async(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.New_Port_0Soap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.New_Port_0Soap))
            {
                return new System.ServiceModel.EndpointAddress("http://coetaars1.coe.ads/arsys/services/ARService?server=coetaars2&webService=COE" +
                        "_WOI_WorkOrderInterface_WS");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return New_Port_0PortTypeClient.GetBindingForEndpoint(EndpointConfiguration.New_Port_0Soap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return New_Port_0PortTypeClient.GetEndpointAddress(EndpointConfiguration.New_Port_0Soap);
        }
        
        public enum EndpointConfiguration
        {
            
            New_Port_0Soap,
        }
    }
}
