//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COE_WOI_WorkOrderInterface_WS
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", ConfigurationName="COE_WOI_WorkOrderInterface_WS.New_Port_0PortType")]
    public interface New_Port_0PortType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:COE_WOI_WorkOrderInterface_WS/New_Create_Operation_0", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<COE_WOI_WorkOrderInterface_WS.New_Create_Operation_0Response> New_Create_Operation_0Async(COE_WOI_WorkOrderInterface_WS.New_Create_Operation_0Request request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS")]
    public partial class AuthenticationInfo
    {
        
        private string userNameField;
        
        private string passwordField;
        
        private string authenticationField;
        
        private string localeField;
        
        private string timeZoneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string userName
        {
            get
            {
                return this.userNameField;
            }
            set
            {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string authentication
        {
            get
            {
                return this.authenticationField;
            }
            set
            {
                this.authenticationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string locale
        {
            get
            {
                return this.localeField;
            }
            set
            {
                this.localeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string timeZone
        {
            get
            {
                return this.timeZoneField;
            }
            set
            {
                this.timeZoneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS")]
    public enum Requested_ForType
    {
        
        /// <remarks/>
        Individual,
        
        /// <remarks/>
        Organization,
        
        /// <remarks/>
        Department,
        
        /// <remarks/>
        Company,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="New_Create_Operation_0", WrapperNamespace="urn:COE_WOI_WorkOrderInterface_WS", IsWrapped=true)]
    public partial class New_Create_Operation_0Request
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS")]
        public COE_WOI_WorkOrderInterface_WS.AuthenticationInfo AuthenticationInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=0)]
        public string Customer_Company;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=1)]
        public string Customer_Login_ID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=2)]
        public string z1D_Action;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=3)]
        public string Summary;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=4)]
        public string Description;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<Requested_ForType> Requested_For;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=6)]
        public string Location_Company;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=7)]
        public string Work_Order_Template_Used;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=8)]
        public string TemplateName;
        
        public New_Create_Operation_0Request()
        {
        }
        
        public New_Create_Operation_0Request(COE_WOI_WorkOrderInterface_WS.AuthenticationInfo AuthenticationInfo, string Customer_Company, string Customer_Login_ID, string z1D_Action, string Summary, string Description, System.Nullable<Requested_ForType> Requested_For, string Location_Company, string Work_Order_Template_Used, string TemplateName)
        {
            this.AuthenticationInfo = AuthenticationInfo;
            this.Customer_Company = Customer_Company;
            this.Customer_Login_ID = Customer_Login_ID;
            this.z1D_Action = z1D_Action;
            this.Summary = Summary;
            this.Description = Description;
            this.Requested_For = Requested_For;
            this.Location_Company = Location_Company;
            this.Work_Order_Template_Used = Work_Order_Template_Used;
            this.TemplateName = TemplateName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="New_Create_Operation_0Response", WrapperNamespace="urn:COE_WOI_WorkOrderInterface_WS", IsWrapped=true)]
    public partial class New_Create_Operation_0Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:COE_WOI_WorkOrderInterface_WS", Order=0)]
        public string InstanceId;
        
        public New_Create_Operation_0Response()
        {
        }
        
        public New_Create_Operation_0Response(string InstanceId)
        {
            this.InstanceId = InstanceId;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public interface New_Port_0PortTypeChannel : COE_WOI_WorkOrderInterface_WS.New_Port_0PortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public partial class New_Port_0PortTypeClient : System.ServiceModel.ClientBase<COE_WOI_WorkOrderInterface_WS.New_Port_0PortType>, COE_WOI_WorkOrderInterface_WS.New_Port_0PortType
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public New_Port_0PortTypeClient() : 
                base(New_Port_0PortTypeClient.GetDefaultBinding(), New_Port_0PortTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.New_Port_0Soap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public New_Port_0PortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(New_Port_0PortTypeClient.GetBindingForEndpoint(endpointConfiguration), New_Port_0PortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public New_Port_0PortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(New_Port_0PortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public New_Port_0PortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(New_Port_0PortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public New_Port_0PortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<COE_WOI_WorkOrderInterface_WS.New_Create_Operation_0Response> COE_WOI_WorkOrderInterface_WS.New_Port_0PortType.New_Create_Operation_0Async(COE_WOI_WorkOrderInterface_WS.New_Create_Operation_0Request request)
        {
            return base.Channel.New_Create_Operation_0Async(request);
        }
        
        public System.Threading.Tasks.Task<COE_WOI_WorkOrderInterface_WS.New_Create_Operation_0Response> New_Create_Operation_0Async(COE_WOI_WorkOrderInterface_WS.AuthenticationInfo AuthenticationInfo, string Customer_Company, string Customer_Login_ID, string z1D_Action, string Summary, string Description, System.Nullable<Requested_ForType> Requested_For, string Location_Company, string Work_Order_Template_Used, string TemplateName)
        {
            COE_WOI_WorkOrderInterface_WS.New_Create_Operation_0Request inValue = new COE_WOI_WorkOrderInterface_WS.New_Create_Operation_0Request();
            inValue.AuthenticationInfo = AuthenticationInfo;
            inValue.Customer_Company = Customer_Company;
            inValue.Customer_Login_ID = Customer_Login_ID;
            inValue.z1D_Action = z1D_Action;
            inValue.Summary = Summary;
            inValue.Description = Description;
            inValue.Requested_For = Requested_For;
            inValue.Location_Company = Location_Company;
            inValue.Work_Order_Template_Used = Work_Order_Template_Used;
            inValue.TemplateName = TemplateName;
            return ((COE_WOI_WorkOrderInterface_WS.New_Port_0PortType)(this)).New_Create_Operation_0Async(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.New_Port_0Soap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.New_Port_0Soap))
            {
                return new System.ServiceModel.EndpointAddress("http://coetaars1.coe.ads/arsys/services/ARService?server=coetaars2&webService=COE" +
                        "_WOI_WorkOrderInterface_WS");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return New_Port_0PortTypeClient.GetBindingForEndpoint(EndpointConfiguration.New_Port_0Soap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return New_Port_0PortTypeClient.GetEndpointAddress(EndpointConfiguration.New_Port_0Soap);
        }
        
        public enum EndpointConfiguration
        {
            
            New_Port_0Soap,
        }
    }
}
