//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoE.Issues.Remedy.Watcher.RemedyServiceReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:HPD_IncidentInterface_Create_WS", ConfigurationName="CoE.Issues.Remedy.Watcher.RemedyServiceReference.HPD_IncidentInterface_Create_WSP" +
        "ortTypePortType")]
    public interface HPD_IncidentInterface_Create_WSPortTypePortType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:HPD_IncidentInterface_Create_WS/HelpDesk_Submit_Service", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CoE.Issues.Remedy.Watcher.RemedyServiceReference.HelpDesk_Submit_ServiceResponse> HelpDesk_Submit_ServiceAsync(CoE.Issues.Remedy.Watcher.RemedyServiceReference.HelpDesk_Submit_ServiceRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:HPD_IncidentInterface_Create_WS")]
    public partial class AuthenticationInfo
    {
        
        private string userNameField;
        
        private string passwordField;
        
        private string authenticationField;
        
        private string localeField;
        
        private string timeZoneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string userName
        {
            get
            {
                return this.userNameField;
            }
            set
            {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string authentication
        {
            get
            {
                return this.authenticationField;
            }
            set
            {
                this.authenticationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string locale
        {
            get
            {
                return this.localeField;
            }
            set
            {
                this.localeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string timeZone
        {
            get
            {
                return this.timeZoneField;
            }
            set
            {
                this.timeZoneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:HPD_IncidentInterface_Create_WS")]
    public enum ImpactType
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1-Extensive/Widespread")]
        Item1ExtensiveWidespread,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2-Significant/Large")]
        Item2SignificantLarge,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3-Moderate/Limited")]
        Item3ModerateLimited,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4-Minor/Localized")]
        Item4MinorLocalized,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:HPD_IncidentInterface_Create_WS")]
    public enum Reported_SourceType
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Direct Input")]
        DirectInput,
        
        /// <remarks/>
        Email,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("External Escalation")]
        ExternalEscalation,
        
        /// <remarks/>
        Fax,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Self Service")]
        SelfService,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Systems Management")]
        SystemsManagement,
        
        /// <remarks/>
        Phone,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Voice Mail")]
        VoiceMail,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Walk In")]
        WalkIn,
        
        /// <remarks/>
        Web,
        
        /// <remarks/>
        Other,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("BMC Impact Manager Event")]
        BMCImpactManagerEvent,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:HPD_IncidentInterface_Create_WS")]
    public enum Service_TypeType
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("User Service Restoration")]
        UserServiceRestoration,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("User Service Request")]
        UserServiceRequest,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Infrastructure Restoration")]
        InfrastructureRestoration,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Infrastructure Event")]
        InfrastructureEvent,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:HPD_IncidentInterface_Create_WS")]
    public enum StatusType
    {
        
        /// <remarks/>
        New,
        
        /// <remarks/>
        Assigned,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("In Progress")]
        InProgress,
        
        /// <remarks/>
        Pending,
        
        /// <remarks/>
        Resolved,
        
        /// <remarks/>
        Closed,
        
        /// <remarks/>
        Cancelled,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:HPD_IncidentInterface_Create_WS")]
    public enum Create_RequestType
    {
        
        /// <remarks/>
        Yes,
        
        /// <remarks/>
        No,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:HPD_IncidentInterface_Create_WS")]
    public enum UrgencyType
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1-Critical")]
        Item1Critical,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2-High")]
        Item2High,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3-Medium")]
        Item3Medium,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4-Low")]
        Item4Low,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:HPD_IncidentInterface_Create_WS")]
    public enum Work_Info_TypeType
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("----- Customer Inbound -----")]
        CustomerInbound,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Customer Communication")]
        CustomerCommunication,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Customer Follow-up")]
        CustomerFollowup,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Customer Status Update")]
        CustomerStatusUpdate,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("----- Customer Outbound -----")]
        CustomerOutbound,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Closure Follow Up")]
        ClosureFollowUp,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Detail Clarification")]
        DetailClarification,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("General Information")]
        GeneralInformation,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Resolution Communications")]
        ResolutionCommunications,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Satisfaction Survey")]
        SatisfactionSurvey,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Status Update")]
        StatusUpdate,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("----- General -----")]
        General,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Incident Task / Action")]
        IncidentTaskAction,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Problem Script")]
        ProblemScript,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Working Log")]
        WorkingLog,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Email System")]
        EmailSystem,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Paging System")]
        PagingSystem,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("BMC Impact Manager Update")]
        BMCImpactManagerUpdate,
        
        /// <remarks/>
        Chat,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:HPD_IncidentInterface_Create_WS")]
    public enum Work_Info_SourceType
    {
        
        /// <remarks/>
        Email,
        
        /// <remarks/>
        Fax,
        
        /// <remarks/>
        Phone,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Voice Mail")]
        VoiceMail,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Walk In")]
        WalkIn,
        
        /// <remarks/>
        Pager,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("System Assignment")]
        SystemAssignment,
        
        /// <remarks/>
        Web,
        
        /// <remarks/>
        Other,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("BMC Impact Manager Event")]
        BMCImpactManagerEvent,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:HPD_IncidentInterface_Create_WS")]
    public enum Work_Info_View_AccessType
    {
        
        /// <remarks/>
        Internal,
        
        /// <remarks/>
        Public,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:HPD_IncidentInterface_Create_WS")]
    public enum Status_ReasonType
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Infrastructure Change Created")]
        InfrastructureChangeCreated,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Local Site Action Required")]
        LocalSiteActionRequired,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Purchase Order Approval")]
        PurchaseOrderApproval,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Registration Approval")]
        RegistrationApproval,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Supplier Delivery")]
        SupplierDelivery,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Support Contact Hold")]
        SupportContactHold,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Third Party Vendor Action Reqd")]
        ThirdPartyVendorActionReqd,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Client Action Required")]
        ClientActionRequired,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Infrastructure Change")]
        InfrastructureChange,
        
        /// <remarks/>
        Request,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Future Enhancement")]
        FutureEnhancement,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Pending Original Incident")]
        PendingOriginalIncident,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Client Hold")]
        ClientHold,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Monitoring Incident")]
        MonitoringIncident,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Customer Follow-Up Required")]
        CustomerFollowUpRequired,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Temporary Corrective Action")]
        TemporaryCorrectiveAction,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("No Further Action Required")]
        NoFurtherActionRequired,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Resolved by Original Incident")]
        ResolvedbyOriginalIncident,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Automated Resolution Reported")]
        AutomatedResolutionReported,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("No longer a Causal CI")]
        NolongeraCausalCI,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HelpDesk_Submit_Service", WrapperNamespace="urn:HPD_IncidentInterface_Create_WS", IsWrapped=true)]
    public partial class HelpDesk_Submit_ServiceRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:HPD_IncidentInterface_Create_WS")]
        public CoE.Issues.Remedy.Watcher.RemedyServiceReference.AuthenticationInfo AuthenticationInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_Create_WS", Order=0)]
        public string Assigned_Group;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_Create_WS", Order=1)]
        public string Assigned_Group_Shift_Name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_Create_WS", Order=2)]
        public string Assigned_Support_Company;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_Create_WS", Order=3)]
        public string Assigned_Support_Organization;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_Create_WS", Order=4)]
        public string Assignee;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_Create_WS", Order=5)]
        public string Categorization_Tier_1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_Create_WS", Order=6)]
        public string Categorization_Tier_2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_Create_WS", Order=7)]
        public string Categorization_Tier_3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_Create_WS", Order=8)]
        public string CI_Name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_Create_WS", Order=9)]
        public string Closure_Manufacturer;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_Create_WS", Order=10)]
        public string Closure_Product_Category_Tier1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_Create_WS", Order=11)]
        public string Closure_Product_Category_Tier2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_Create_WS", Order=12)]
        public string Closure_Product_Category_Tier3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_Create_WS", Order=13)]
        public string Closure_Product_Model_Version;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_Create_WS", Order=14)]
        public string Closure_Product_Name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_Create_WS", Order=15)]
        public string Department;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_Create_WS", Order=16)]
        public string First_Name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_Create_WS", Order=17)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<ImpactType> Impact;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_Create_WS", Order=18)]
        public string Last_Name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_Create_WS", Order=19)]
        public string Lookup_Keyword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_Create_WS", Order=20)]
        public string Manufacturer;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_Create_WS", Order=21)]
        public string Product_Categorization_Tier_1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_Create_WS", Order=22)]
        public string Product_Categorization_Tier_2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_Create_WS", Order=23)]
        public string Product_Categorization_Tier_3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_Create_WS", Order=24)]
        public string Product_Model_Version;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_Create_WS", Order=25)]
        public string Product_Name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_Create_WS", Order=26)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<Reported_SourceType> Reported_Source;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_Create_WS", Order=27)]
        public string Resolution;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_Create_WS", Order=28)]
        public string Resolution_Category_Tier_1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_Create_WS", Order=29)]
        public string Resolution_Category_Tier_2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_Create_WS", Order=30)]
        public string Resolution_Category_Tier_3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_Create_WS", Order=31)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<Service_TypeType> Service_Type;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_Create_WS", Order=32)]
        public CoE.Issues.Remedy.Watcher.RemedyServiceReference.StatusType Status;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_Create_WS", Order=33)]
        public string Action;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_Create_WS", Order=34)]
        public CoE.Issues.Remedy.Watcher.RemedyServiceReference.Create_RequestType Create_Request;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_Create_WS", Order=35)]
        public string Summary;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_Create_WS", Order=36)]
        public string Notes;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_Create_WS", Order=37)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<UrgencyType> Urgency;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_Create_WS", Order=38)]
        public string Work_Info_Summary;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_Create_WS", Order=39)]
        public string Work_Info_Notes;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_Create_WS", Order=40)]
        public CoE.Issues.Remedy.Watcher.RemedyServiceReference.Work_Info_TypeType Work_Info_Type;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_Create_WS", Order=41)]
        public System.DateTime Work_Info_Date;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_Create_WS", Order=42)]
        public CoE.Issues.Remedy.Watcher.RemedyServiceReference.Work_Info_SourceType Work_Info_Source;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_Create_WS", Order=43)]
        [System.ComponentModel.DefaultValueAttribute(Create_RequestType.No)]
        public CoE.Issues.Remedy.Watcher.RemedyServiceReference.Create_RequestType Work_Info_Locked;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_Create_WS", Order=44)]
        [System.ComponentModel.DefaultValueAttribute(Work_Info_View_AccessType.Internal)]
        public CoE.Issues.Remedy.Watcher.RemedyServiceReference.Work_Info_View_AccessType Work_Info_View_Access;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_Create_WS", Order=45)]
        public string Middle_Initial;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_Create_WS", Order=46)]
        public CoE.Issues.Remedy.Watcher.RemedyServiceReference.Status_ReasonType Status_Reason;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_Create_WS", Order=47)]
        public string Direct_Contact_First_Name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_Create_WS", Order=48)]
        public string Direct_Contact_Middle_Initial;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_Create_WS", Order=49)]
        public string Direct_Contact_Last_Name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_Create_WS", Order=50)]
        public string TemplateID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_Create_WS", Order=51)]
        public string ServiceCI;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_Create_WS", Order=52)]
        public string ServiceCI_ReconID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_Create_WS", Order=53)]
        public string HPD_CI;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_Create_WS", Order=54)]
        public string HPD_CI_ReconID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_Create_WS", Order=55)]
        public string HPD_CI_FormName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_Create_WS", Order=56)]
        public string WorkInfoAttachment1Name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_Create_WS", Order=57)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] WorkInfoAttachment1Data;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_Create_WS", Order=58)]
        public int WorkInfoAttachment1OrigSize;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_Create_WS", Order=59)]
        public string Login_ID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_Create_WS", Order=60)]
        public string Customer_Company;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_Create_WS", Order=61)]
        public string Corporate_ID;
        
        public HelpDesk_Submit_ServiceRequest()
        {
        }
        
        public HelpDesk_Submit_ServiceRequest(
                    CoE.Issues.Remedy.Watcher.RemedyServiceReference.AuthenticationInfo AuthenticationInfo, 
                    string Assigned_Group, 
                    string Assigned_Group_Shift_Name, 
                    string Assigned_Support_Company, 
                    string Assigned_Support_Organization, 
                    string Assignee, 
                    string Categorization_Tier_1, 
                    string Categorization_Tier_2, 
                    string Categorization_Tier_3, 
                    string CI_Name, 
                    string Closure_Manufacturer, 
                    string Closure_Product_Category_Tier1, 
                    string Closure_Product_Category_Tier2, 
                    string Closure_Product_Category_Tier3, 
                    string Closure_Product_Model_Version, 
                    string Closure_Product_Name, 
                    string Department, 
                    string First_Name, 
                    System.Nullable<ImpactType> Impact, 
                    string Last_Name, 
                    string Lookup_Keyword, 
                    string Manufacturer, 
                    string Product_Categorization_Tier_1, 
                    string Product_Categorization_Tier_2, 
                    string Product_Categorization_Tier_3, 
                    string Product_Model_Version, 
                    string Product_Name, 
                    System.Nullable<Reported_SourceType> Reported_Source, 
                    string Resolution, 
                    string Resolution_Category_Tier_1, 
                    string Resolution_Category_Tier_2, 
                    string Resolution_Category_Tier_3, 
                    System.Nullable<Service_TypeType> Service_Type, 
                    CoE.Issues.Remedy.Watcher.RemedyServiceReference.StatusType Status, 
                    string Action, 
                    CoE.Issues.Remedy.Watcher.RemedyServiceReference.Create_RequestType Create_Request, 
                    string Summary, 
                    string Notes, 
                    System.Nullable<UrgencyType> Urgency, 
                    string Work_Info_Summary, 
                    string Work_Info_Notes, 
                    CoE.Issues.Remedy.Watcher.RemedyServiceReference.Work_Info_TypeType Work_Info_Type, 
                    System.DateTime Work_Info_Date, 
                    CoE.Issues.Remedy.Watcher.RemedyServiceReference.Work_Info_SourceType Work_Info_Source, 
                    CoE.Issues.Remedy.Watcher.RemedyServiceReference.Create_RequestType Work_Info_Locked, 
                    CoE.Issues.Remedy.Watcher.RemedyServiceReference.Work_Info_View_AccessType Work_Info_View_Access, 
                    string Middle_Initial, 
                    CoE.Issues.Remedy.Watcher.RemedyServiceReference.Status_ReasonType Status_Reason, 
                    string Direct_Contact_First_Name, 
                    string Direct_Contact_Middle_Initial, 
                    string Direct_Contact_Last_Name, 
                    string TemplateID, 
                    string ServiceCI, 
                    string ServiceCI_ReconID, 
                    string HPD_CI, 
                    string HPD_CI_ReconID, 
                    string HPD_CI_FormName, 
                    string WorkInfoAttachment1Name, 
                    byte[] WorkInfoAttachment1Data, 
                    int WorkInfoAttachment1OrigSize, 
                    string Login_ID, 
                    string Customer_Company, 
                    string Corporate_ID)
        {
            this.AuthenticationInfo = AuthenticationInfo;
            this.Assigned_Group = Assigned_Group;
            this.Assigned_Group_Shift_Name = Assigned_Group_Shift_Name;
            this.Assigned_Support_Company = Assigned_Support_Company;
            this.Assigned_Support_Organization = Assigned_Support_Organization;
            this.Assignee = Assignee;
            this.Categorization_Tier_1 = Categorization_Tier_1;
            this.Categorization_Tier_2 = Categorization_Tier_2;
            this.Categorization_Tier_3 = Categorization_Tier_3;
            this.CI_Name = CI_Name;
            this.Closure_Manufacturer = Closure_Manufacturer;
            this.Closure_Product_Category_Tier1 = Closure_Product_Category_Tier1;
            this.Closure_Product_Category_Tier2 = Closure_Product_Category_Tier2;
            this.Closure_Product_Category_Tier3 = Closure_Product_Category_Tier3;
            this.Closure_Product_Model_Version = Closure_Product_Model_Version;
            this.Closure_Product_Name = Closure_Product_Name;
            this.Department = Department;
            this.First_Name = First_Name;
            this.Impact = Impact;
            this.Last_Name = Last_Name;
            this.Lookup_Keyword = Lookup_Keyword;
            this.Manufacturer = Manufacturer;
            this.Product_Categorization_Tier_1 = Product_Categorization_Tier_1;
            this.Product_Categorization_Tier_2 = Product_Categorization_Tier_2;
            this.Product_Categorization_Tier_3 = Product_Categorization_Tier_3;
            this.Product_Model_Version = Product_Model_Version;
            this.Product_Name = Product_Name;
            this.Reported_Source = Reported_Source;
            this.Resolution = Resolution;
            this.Resolution_Category_Tier_1 = Resolution_Category_Tier_1;
            this.Resolution_Category_Tier_2 = Resolution_Category_Tier_2;
            this.Resolution_Category_Tier_3 = Resolution_Category_Tier_3;
            this.Service_Type = Service_Type;
            this.Status = Status;
            this.Action = Action;
            this.Create_Request = Create_Request;
            this.Summary = Summary;
            this.Notes = Notes;
            this.Urgency = Urgency;
            this.Work_Info_Summary = Work_Info_Summary;
            this.Work_Info_Notes = Work_Info_Notes;
            this.Work_Info_Type = Work_Info_Type;
            this.Work_Info_Date = Work_Info_Date;
            this.Work_Info_Source = Work_Info_Source;
            this.Work_Info_Locked = Work_Info_Locked;
            this.Work_Info_View_Access = Work_Info_View_Access;
            this.Middle_Initial = Middle_Initial;
            this.Status_Reason = Status_Reason;
            this.Direct_Contact_First_Name = Direct_Contact_First_Name;
            this.Direct_Contact_Middle_Initial = Direct_Contact_Middle_Initial;
            this.Direct_Contact_Last_Name = Direct_Contact_Last_Name;
            this.TemplateID = TemplateID;
            this.ServiceCI = ServiceCI;
            this.ServiceCI_ReconID = ServiceCI_ReconID;
            this.HPD_CI = HPD_CI;
            this.HPD_CI_ReconID = HPD_CI_ReconID;
            this.HPD_CI_FormName = HPD_CI_FormName;
            this.WorkInfoAttachment1Name = WorkInfoAttachment1Name;
            this.WorkInfoAttachment1Data = WorkInfoAttachment1Data;
            this.WorkInfoAttachment1OrigSize = WorkInfoAttachment1OrigSize;
            this.Login_ID = Login_ID;
            this.Customer_Company = Customer_Company;
            this.Corporate_ID = Corporate_ID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HelpDesk_Submit_ServiceResponse", WrapperNamespace="urn:HPD_IncidentInterface_Create_WS", IsWrapped=true)]
    public partial class HelpDesk_Submit_ServiceResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:HPD_IncidentInterface_Create_WS", Order=0)]
        public string Incident_Number;
        
        public HelpDesk_Submit_ServiceResponse()
        {
        }
        
        public HelpDesk_Submit_ServiceResponse(string Incident_Number)
        {
            this.Incident_Number = Incident_Number;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public interface HPD_IncidentInterface_Create_WSPortTypePortTypeChannel : CoE.Issues.Remedy.Watcher.RemedyServiceReference.HPD_IncidentInterface_Create_WSPortTypePortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public partial class HPD_IncidentInterface_Create_WSPortTypePortTypeClient : System.ServiceModel.ClientBase<CoE.Issues.Remedy.Watcher.RemedyServiceReference.HPD_IncidentInterface_Create_WSPortTypePortType>, CoE.Issues.Remedy.Watcher.RemedyServiceReference.HPD_IncidentInterface_Create_WSPortTypePortType
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public HPD_IncidentInterface_Create_WSPortTypePortTypeClient() : 
                base(HPD_IncidentInterface_Create_WSPortTypePortTypeClient.GetDefaultBinding(), HPD_IncidentInterface_Create_WSPortTypePortTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.HPD_IncidentInterface_Create_WSPortTypeSoap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HPD_IncidentInterface_Create_WSPortTypePortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(HPD_IncidentInterface_Create_WSPortTypePortTypeClient.GetBindingForEndpoint(endpointConfiguration), HPD_IncidentInterface_Create_WSPortTypePortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HPD_IncidentInterface_Create_WSPortTypePortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(HPD_IncidentInterface_Create_WSPortTypePortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HPD_IncidentInterface_Create_WSPortTypePortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(HPD_IncidentInterface_Create_WSPortTypePortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HPD_IncidentInterface_Create_WSPortTypePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CoE.Issues.Remedy.Watcher.RemedyServiceReference.HelpDesk_Submit_ServiceResponse> CoE.Issues.Remedy.Watcher.RemedyServiceReference.HPD_IncidentInterface_Create_WSPortTypePortType.HelpDesk_Submit_ServiceAsync(CoE.Issues.Remedy.Watcher.RemedyServiceReference.HelpDesk_Submit_ServiceRequest request)
        {
            return base.Channel.HelpDesk_Submit_ServiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<CoE.Issues.Remedy.Watcher.RemedyServiceReference.HelpDesk_Submit_ServiceResponse> HelpDesk_Submit_ServiceAsync(
                    CoE.Issues.Remedy.Watcher.RemedyServiceReference.AuthenticationInfo AuthenticationInfo, 
                    string Assigned_Group, 
                    string Assigned_Group_Shift_Name, 
                    string Assigned_Support_Company, 
                    string Assigned_Support_Organization, 
                    string Assignee, 
                    string Categorization_Tier_1, 
                    string Categorization_Tier_2, 
                    string Categorization_Tier_3, 
                    string CI_Name, 
                    string Closure_Manufacturer, 
                    string Closure_Product_Category_Tier1, 
                    string Closure_Product_Category_Tier2, 
                    string Closure_Product_Category_Tier3, 
                    string Closure_Product_Model_Version, 
                    string Closure_Product_Name, 
                    string Department, 
                    string First_Name, 
                    System.Nullable<ImpactType> Impact, 
                    string Last_Name, 
                    string Lookup_Keyword, 
                    string Manufacturer, 
                    string Product_Categorization_Tier_1, 
                    string Product_Categorization_Tier_2, 
                    string Product_Categorization_Tier_3, 
                    string Product_Model_Version, 
                    string Product_Name, 
                    System.Nullable<Reported_SourceType> Reported_Source, 
                    string Resolution, 
                    string Resolution_Category_Tier_1, 
                    string Resolution_Category_Tier_2, 
                    string Resolution_Category_Tier_3, 
                    System.Nullable<Service_TypeType> Service_Type, 
                    CoE.Issues.Remedy.Watcher.RemedyServiceReference.StatusType Status, 
                    string Action, 
                    CoE.Issues.Remedy.Watcher.RemedyServiceReference.Create_RequestType Create_Request, 
                    string Summary, 
                    string Notes, 
                    System.Nullable<UrgencyType> Urgency, 
                    string Work_Info_Summary, 
                    string Work_Info_Notes, 
                    CoE.Issues.Remedy.Watcher.RemedyServiceReference.Work_Info_TypeType Work_Info_Type, 
                    System.DateTime Work_Info_Date, 
                    CoE.Issues.Remedy.Watcher.RemedyServiceReference.Work_Info_SourceType Work_Info_Source, 
                    CoE.Issues.Remedy.Watcher.RemedyServiceReference.Create_RequestType Work_Info_Locked, 
                    CoE.Issues.Remedy.Watcher.RemedyServiceReference.Work_Info_View_AccessType Work_Info_View_Access, 
                    string Middle_Initial, 
                    CoE.Issues.Remedy.Watcher.RemedyServiceReference.Status_ReasonType Status_Reason, 
                    string Direct_Contact_First_Name, 
                    string Direct_Contact_Middle_Initial, 
                    string Direct_Contact_Last_Name, 
                    string TemplateID, 
                    string ServiceCI, 
                    string ServiceCI_ReconID, 
                    string HPD_CI, 
                    string HPD_CI_ReconID, 
                    string HPD_CI_FormName, 
                    string WorkInfoAttachment1Name, 
                    byte[] WorkInfoAttachment1Data, 
                    int WorkInfoAttachment1OrigSize, 
                    string Login_ID, 
                    string Customer_Company, 
                    string Corporate_ID)
        {
            CoE.Issues.Remedy.Watcher.RemedyServiceReference.HelpDesk_Submit_ServiceRequest inValue = new CoE.Issues.Remedy.Watcher.RemedyServiceReference.HelpDesk_Submit_ServiceRequest();
            inValue.AuthenticationInfo = AuthenticationInfo;
            inValue.Assigned_Group = Assigned_Group;
            inValue.Assigned_Group_Shift_Name = Assigned_Group_Shift_Name;
            inValue.Assigned_Support_Company = Assigned_Support_Company;
            inValue.Assigned_Support_Organization = Assigned_Support_Organization;
            inValue.Assignee = Assignee;
            inValue.Categorization_Tier_1 = Categorization_Tier_1;
            inValue.Categorization_Tier_2 = Categorization_Tier_2;
            inValue.Categorization_Tier_3 = Categorization_Tier_3;
            inValue.CI_Name = CI_Name;
            inValue.Closure_Manufacturer = Closure_Manufacturer;
            inValue.Closure_Product_Category_Tier1 = Closure_Product_Category_Tier1;
            inValue.Closure_Product_Category_Tier2 = Closure_Product_Category_Tier2;
            inValue.Closure_Product_Category_Tier3 = Closure_Product_Category_Tier3;
            inValue.Closure_Product_Model_Version = Closure_Product_Model_Version;
            inValue.Closure_Product_Name = Closure_Product_Name;
            inValue.Department = Department;
            inValue.First_Name = First_Name;
            inValue.Impact = Impact;
            inValue.Last_Name = Last_Name;
            inValue.Lookup_Keyword = Lookup_Keyword;
            inValue.Manufacturer = Manufacturer;
            inValue.Product_Categorization_Tier_1 = Product_Categorization_Tier_1;
            inValue.Product_Categorization_Tier_2 = Product_Categorization_Tier_2;
            inValue.Product_Categorization_Tier_3 = Product_Categorization_Tier_3;
            inValue.Product_Model_Version = Product_Model_Version;
            inValue.Product_Name = Product_Name;
            inValue.Reported_Source = Reported_Source;
            inValue.Resolution = Resolution;
            inValue.Resolution_Category_Tier_1 = Resolution_Category_Tier_1;
            inValue.Resolution_Category_Tier_2 = Resolution_Category_Tier_2;
            inValue.Resolution_Category_Tier_3 = Resolution_Category_Tier_3;
            inValue.Service_Type = Service_Type;
            inValue.Status = Status;
            inValue.Action = Action;
            inValue.Create_Request = Create_Request;
            inValue.Summary = Summary;
            inValue.Notes = Notes;
            inValue.Urgency = Urgency;
            inValue.Work_Info_Summary = Work_Info_Summary;
            inValue.Work_Info_Notes = Work_Info_Notes;
            inValue.Work_Info_Type = Work_Info_Type;
            inValue.Work_Info_Date = Work_Info_Date;
            inValue.Work_Info_Source = Work_Info_Source;
            inValue.Work_Info_Locked = Work_Info_Locked;
            inValue.Work_Info_View_Access = Work_Info_View_Access;
            inValue.Middle_Initial = Middle_Initial;
            inValue.Status_Reason = Status_Reason;
            inValue.Direct_Contact_First_Name = Direct_Contact_First_Name;
            inValue.Direct_Contact_Middle_Initial = Direct_Contact_Middle_Initial;
            inValue.Direct_Contact_Last_Name = Direct_Contact_Last_Name;
            inValue.TemplateID = TemplateID;
            inValue.ServiceCI = ServiceCI;
            inValue.ServiceCI_ReconID = ServiceCI_ReconID;
            inValue.HPD_CI = HPD_CI;
            inValue.HPD_CI_ReconID = HPD_CI_ReconID;
            inValue.HPD_CI_FormName = HPD_CI_FormName;
            inValue.WorkInfoAttachment1Name = WorkInfoAttachment1Name;
            inValue.WorkInfoAttachment1Data = WorkInfoAttachment1Data;
            inValue.WorkInfoAttachment1OrigSize = WorkInfoAttachment1OrigSize;
            inValue.Login_ID = Login_ID;
            inValue.Customer_Company = Customer_Company;
            inValue.Corporate_ID = Corporate_ID;
            return ((CoE.Issues.Remedy.Watcher.RemedyServiceReference.HPD_IncidentInterface_Create_WSPortTypePortType)(this)).HelpDesk_Submit_ServiceAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.HPD_IncidentInterface_Create_WSPortTypeSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.HPD_IncidentInterface_Create_WSPortTypeSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://coetaars1.coe.ads/arsys/services/ARService?server=coetaars2&webService=HPD" +
                        "_IncidentInterface_Create_WS");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return HPD_IncidentInterface_Create_WSPortTypePortTypeClient.GetBindingForEndpoint(EndpointConfiguration.HPD_IncidentInterface_Create_WSPortTypeSoap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return HPD_IncidentInterface_Create_WSPortTypePortTypeClient.GetEndpointAddress(EndpointConfiguration.HPD_IncidentInterface_Create_WSPortTypeSoap);
        }
        
        public enum EndpointConfiguration
        {
            
            HPD_IncidentInterface_Create_WSPortTypeSoap,
        }
    }
}
